# Generated by Django 6.0.3 on 2026-04-02 18:16

from decimal import Decimal

from django.db import migrations


def seed_pricing_content(apps, schema_editor):
    CTABlock = apps.get_model('main', 'CTABlock')
    Testimonial = apps.get_model('main', 'Testimonial')
    ComparisonFeature = apps.get_model('price', 'ComparisonFeature')
    PlanFeature = apps.get_model('price', 'PlanFeature')
    PricingFAQ = apps.get_model('price', 'PricingFAQ')
    PricingPageSettings = apps.get_model('price', 'PricingPageSettings')
    PricingPlan = apps.get_model('price', 'PricingPlan')

    PricingPageSettings.objects.update_or_create(
        pk=1,
        defaults={
            'title': 'خطط مرنة تناسب احتياجاتك',
            'subtitle': 'الأسعار والباقات',
            'description': 'اختر الخطة المناسبة لتحقيق أهدافك التعليمية. نوفر خيارات متنوعة تناسب مختلف الميزانيات والاحتياجات مع ضمان الجودة العالية.',
            'meta_title': 'الأسعار والباقات | أكاديمية سنا',
            'meta_description': 'خطط مرنة وباقات تعليمية تناسب مختلف الاحتياجات في أكاديمية سنا.',
        },
    )

    plans = [
        (
            'الباقة الأساسية',
            'الباقة-الأساسية',
            Decimal('150.00'),
            'ر.س / الحصة',
            'مثالية للطلاب الذين يحتاجون دعمًا دوريًا',
            'ابدأ الآن',
            '/contact/',
            False,
            1,
            [
                ('حصة خاصة مباشرة ٦٠ دقيقة', True),
                ('معلم متخصص معتمد', True),
                ('تسجيل الحصة للمراجعة', True),
                ('واجبات ومتابعة أساسية', True),
                ('دعم عبر واتساب', True),
                ('تقارير مفصلة', False),
                ('اختبارات تشخيصية', False),
                ('متابعة أولياء الأمور', False),
            ],
        ),
        (
            'الباقة المميزة',
            'الباقة-المميزة',
            Decimal('200.00'),
            'ر.س / الحصة',
            'الخيار الأمثل لتحقيق نتائج ملموسة',
            'ابدأ الآن',
            '/contact/',
            True,
            2,
            [
                ('حصة خاصة مباشرة ٦٠ دقيقة', True),
                ('معلم متخصص معتمد', True),
                ('تسجيل الحصة للمراجعة', True),
                ('واجبات ومتابعة متقدمة', True),
                ('دعم أولوية عبر واتساب', True),
                ('تقارير أسبوعية مفصلة', True),
                ('اختبار تشخيصي أولي', True),
                ('متابعة أولياء الأمور', True),
            ],
        ),
        (
            'الباقة الاحترافية',
            'الباقة-الاحترافية',
            Decimal('300.00'),
            'ر.س / الحصة',
            'للطلاب الذين يهدفون للتفوق المطلق',
            'ابدأ الآن',
            '/contact/',
            False,
            3,
            [
                ('حصة خاصة مباشرة ٧٥ دقيقة', True),
                ('معلم خبير أول', True),
                ('تسجيل الحصة للمراجعة', True),
                ('خطة تعليمية مخصصة', True),
                ('دعم VIP على مدار الساعة', True),
                ('تقارير يومية مفصلة', True),
                ('اختبارات تشخيصية متكررة', True),
                ('جلسة متابعة مع المرشد', True),
            ],
        ),
    ]

    for name, slug, price, billing_period, description, cta_text, cta_url, is_popular, order, features in plans:
        plan, _ = PricingPlan.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'price': price,
                'billing_period': billing_period,
                'description': description,
                'cta_text': cta_text,
                'cta_url': cta_url,
                'is_popular': is_popular,
                'is_active': True,
                'order': order,
            },
        )
        for feature_order, (text, is_included) in enumerate(features, start=1):
            PlanFeature.objects.update_or_create(
                plan=plan,
                text=text,
                defaults={
                    'is_included': is_included,
                    'order': feature_order,
                },
            )

    comparison_rows = [
        ('مدة الحصة', '٦٠ دقيقة', '٦٠ دقيقة', '٧٥ دقيقة'),
        ('نوع المعلم', 'معتمد', 'معتمد', 'خبير أول'),
        ('تسجيل الحصص', 'متاح', 'متاح', 'متاح'),
        ('تقارير المتابعة', '—', 'أسبوعية', 'يومية'),
        ('اختبارات تشخيصية', '—', 'متاح', 'متاح'),
        ('دعم واتساب', 'متاح', 'متاح', 'متاح'),
        ('متابعة ولي الأمر', '—', 'متاح', 'متاح'),
        ('خطة تعليمية مخصصة', '—', '—', 'متاح'),
        ('جلسة مع المرشد', '—', '—', 'متاح'),
    ]
    for order, (label, basic_value, premium_value, professional_value) in enumerate(comparison_rows, start=1):
        ComparisonFeature.objects.update_or_create(
            label=label,
            defaults={
                'basic_value': basic_value,
                'premium_value': premium_value,
                'professional_value': professional_value,
                'order': order,
                'is_active': True,
            },
        )

    pricing_faqs = [
        ('ما هي طرق الدفع المتاحة؟', 'نقبل الدفع ببطاقات مدى وفيزا وماستركارد، بالإضافة إلى التحويل البنكي وApple Pay. يمكن الدفع لكل حصة على حدة أو الاشتراك في باقات شهرية أو مكثفة حسب احتياجك.'),
        ('هل يمكن استرداد المبلغ إذا لم أكن راضيًا؟', 'نعم، نوفر ضمان استرداد خلال أول حصتين إذا لم تكن راضيًا عن التجربة. نرد المبلغ كاملًا دون أي خصومات، لأننا واثقون من جودة خدمتنا ونسعى لبناء ثقة حقيقية مع كل طالب.'),
        ('هل توجد خصومات للباقات المكثفة؟', 'نعم، نوفر خصومات تصل إلى ٢٠٪ عند الاشتراك في باقات من ٨ حصص فأكثر. كما توجد عروض خاصة في مواسم الاختبارات النهائية والقدرات والتحصيلي.'),
        ('هل الحصة التجريبية مجانية؟', 'نعم، نوفر حصة تجريبية مجانية لمدة ٣٠ دقيقة لتتعرف على أسلوب المعلم وتجربة المنصة قبل الالتزام بالاشتراك. يمكنك طلبها من صفحة التواصل أو عبر واتساب.'),
        ('هل يمكنني ترقية الباقة لاحقًا؟', 'بالتأكيد! يمكنك الترقية في أي وقت وسيتم احتساب الفرق فقط. كما يمكنك تغيير الباقة أو إيقاف الاشتراك مؤقتًا حسب ظروفك، مع الحفاظ على رصيدك من الحصص.'),
    ]
    for order, (question, answer) in enumerate(pricing_faqs, start=1):
        PricingFAQ.objects.update_or_create(
            question=question,
            defaults={
                'answer': answer,
                'order': order,
                'is_active': True,
            },
        )

    testimonials = [
        ('سارة المطيري', 'سم', 'ثاني ثانوي', 'رياضيات', 'الاستثمار في الباقة المميزة كان أفضل قرار. التقارير الأسبوعية ساعدتني أتابع تقدمي بشكل واضح.'),
        ('عبدالله الشعلان', 'عش', 'ثالث ثانوي', 'قدرات', 'الباقة الاحترافية تستحق كل ريال. الدعم على مدار الساعة والخطة المخصصة فرقوا معي كثيرًا.'),
        ('نوف الهزاني', 'نه', 'أول ثانوي', 'إنجليزي', 'بدأت بالباقة الأساسية ثم رقيت للمميزة. المرونة في تغيير الباقة سهّلت علي كثير.'),
    ]
    for order, (student_name, initials, level, subject, quote) in enumerate(testimonials, start=1):
        Testimonial.objects.update_or_create(
            student_name=student_name,
            page='pricing',
            defaults={
                'student_initials': initials,
                'level': level,
                'subject': subject,
                'rating': 5,
                'quote': quote,
                'order': order,
                'is_active': True,
                'is_featured': order == 1,
            },
        )

    CTABlock.objects.update_or_create(
        slug='pricing-cta',
        defaults={
            'heading': 'جاهز للبدء؟ احجز حصتك التجريبية المجانية',
            'subheading': 'ابدأ الآن',
            'body_text': 'جرب المنصة والمعلم قبل الالتزام. حصة تجريبية مجانية لمدة ٣٠ دقيقة بدون أي التزام.',
            'primary_cta_text': 'احجز حصة تجريبية',
            'primary_cta_url': '/contact/',
            'secondary_cta_text': 'تواصل عبر الواتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'انضم إلى أكثر من ١٠,٠٠٠ طالب يتعلمون معنا',
            'is_active': True,
        },
    )


def unseed_pricing_content(apps, schema_editor):
    CTABlock = apps.get_model('main', 'CTABlock')
    Testimonial = apps.get_model('main', 'Testimonial')
    ComparisonFeature = apps.get_model('price', 'ComparisonFeature')
    PricingFAQ = apps.get_model('price', 'PricingFAQ')
    PricingPageSettings = apps.get_model('price', 'PricingPageSettings')
    PricingPlan = apps.get_model('price', 'PricingPlan')

    PricingPlan.objects.filter(
        slug__in=['الباقة-الأساسية', 'الباقة-المميزة', 'الباقة-الاحترافية']
    ).delete()
    ComparisonFeature.objects.filter(
        label__in=[
            'مدة الحصة',
            'نوع المعلم',
            'تسجيل الحصص',
            'تقارير المتابعة',
            'اختبارات تشخيصية',
            'دعم واتساب',
            'متابعة ولي الأمر',
            'خطة تعليمية مخصصة',
            'جلسة مع المرشد',
        ]
    ).delete()
    PricingFAQ.objects.filter(
        question__in=[
            'ما هي طرق الدفع المتاحة؟',
            'هل يمكن استرداد المبلغ إذا لم أكن راضيًا؟',
            'هل توجد خصومات للباقات المكثفة؟',
            'هل الحصة التجريبية مجانية؟',
            'هل يمكنني ترقية الباقة لاحقًا؟',
        ]
    ).delete()
    PricingPageSettings.objects.filter(pk=1).delete()
    Testimonial.objects.filter(
        page='pricing',
        student_name__in=['سارة المطيري', 'عبدالله الشعلان', 'نوف الهزاني'],
    ).delete()
    CTABlock.objects.filter(slug='pricing-cta').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_homepage_content'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_pricing_content, unseed_pricing_content),
    ]
