# Generated by Django 6.0.3 on 2026-04-02 17:23

from django.db import migrations


def seed_subject_catalog(apps, schema_editor):
    Subject = apps.get_model('course', 'Subject')

    subjects = [
        ('الرياضيات', 'الرياضيات', 'تأسيس ومتابعة في الرياضيات', 'calculator'),
        ('الفيزياء', 'الفيزياء', 'شرح وتدريب مكثف في الفيزياء', 'atom'),
        ('الكيمياء', 'الكيمياء', 'تبسيط مفاهيم الكيمياء والتجارب', 'beaker'),
        ('اللغة الإنجليزية', 'اللغة-الإنجليزية', 'مهارات اللغة الإنجليزية والاختبارات', 'language'),
        ('اللغة العربية', 'اللغة-العربية', 'مهارات القراءة والكتابة والقواعد', 'book-open'),
        ('الأحياء', 'الأحياء', 'شرح مفاهيم الأحياء بشكل تطبيقي', 'leaf'),
        ('القدرات', 'القدرات', 'استعداد شامل لاختبار القدرات', 'chart-bar'),
        ('التحصيلي', 'التحصيلي', 'مراجعة واختبارات للتحصيلي', 'academic-cap'),
    ]

    for index, (name, slug, description, icon) in enumerate(subjects, start=1):
        Subject.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'icon': icon,
                'order': index,
                'is_active': True,
            },
        )


def unseed_subject_catalog(apps, schema_editor):
    Subject = apps.get_model('course', 'Subject')
    Subject.objects.filter(
        slug__in=[
            'الرياضيات',
            'الفيزياء',
            'الكيمياء',
            'اللغة-الإنجليزية',
            'اللغة-العربية',
            'الأحياء',
            'القدرات',
            'التحصيلي',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_subject_catalog, unseed_subject_catalog),
    ]
