# Generated by Django 6.0.3 on 2026-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='about/')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('header_icon', models.ImageField(blank=True, upload_to='about/')),
                ('primary_cta_text', models.CharField(blank=True, max_length=50)),
                ('primary_cta_url', models.CharField(blank=True, max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Content',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ParentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('feature_type', models.CharField(choices=[('core', 'Core'), ('capability', 'Capability')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['feature_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='about/team/')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
