# Generated by Django 6.0.3 on 2026-04-02 18:35

from django.db import migrations


def seed_about_content(apps, schema_editor):
    Achievement = apps.get_model('about', 'Achievement')
    ContentBlock = apps.get_model('about', 'ContentBlock')
    HowItWorksStep = apps.get_model('about', 'HowItWorksStep')
    PageContent = apps.get_model('about', 'PageContent')
    ParentFeature = apps.get_model('about', 'ParentFeature')
    Statistic = apps.get_model('about', 'Statistic')
    TeamMember = apps.get_model('about', 'TeamMember')
    WhyUsFeature = apps.get_model('about', 'WhyUsFeature')
    CTABlock = apps.get_model('main', 'CTABlock')
    Partner = apps.get_model('main', 'Partner')
    SiteSettings = apps.get_model('main', 'SiteSettings')
    Testimonial = apps.get_model('main', 'Testimonial')

    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            'site_name': 'أكاديمية سنا',
            'accreditation_text': 'أكاديمية سنا معتمدة من الجهات التعليمية المختصة وتلتزم بأعلى معايير الجودة في تقديم الخدمات التعليمية.',
        },
    )

    PageContent.objects.update_or_create(
        slug='about',
        defaults={
            'title': 'من نحن',
            'subtitle': 'أكاديمية سنا هي منصة تعليمية رائدة في المملكة العربية السعودية، نسعى لتقديم تجربة تعليمية استثنائية تجمع بين الجودة والمرونة والثقة.',
            'badge_text': 'منصة تعليمية سعودية',
            'meta_title': 'من نحن | أكاديمية سنا',
            'meta_description': 'تعرف على قصة أكاديمية سنا ورسالتها وفريق القيادة والشركاء المعتمدين.',
        },
    )
    PageContent.objects.update_or_create(
        slug='how-it-works',
        defaults={
            'title': 'ابدأ رحلتك التعليمية في خطوات بسيطة',
            'subtitle': 'من اختيار المادة إلى تحقيق التفوق، نوفر لك تجربة تعليمية متكاملة وواضحة. اتبع هذه الخطوات وابدأ رحلتك معنا اليوم.',
            'badge_text': 'كيف نعمل',
            'primary_cta_text': 'ابدأ الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل معنا',
            'secondary_cta_url': '/contact/',
            'meta_title': 'كيف تعمل أكاديمية سنا | أكاديمية سنا',
            'meta_description': 'استكشف خطوات الحجز والتعلّم والمتابعة داخل أكاديمية سنا.',
        },
    )

    content_blocks = [
        (
            'mission',
            'رسالتنا',
            'تمكين كل طالب في المملكة العربية السعودية من الوصول إلى تعليم عالي الجودة من خلال معلمين معتمدين ومحتوى متوافق مع المناهج الدراسية، مع توفير تجربة تعليمية مرنة تناسب احتياجات كل أسرة.\n\nنؤمن بأن التعليم الجيد حق لجميع الطلاب، ونعمل على جعله متاحًا بأسعار معقولة وجودة لا تضاهى.',
        ),
        (
            'vision',
            'رؤيتنا',
            'أن نكون المنصة التعليمية الأولى في المنطقة العربية، يثق بها أولياء الأمور والطلاب على حد سواء، ونحدث تأثيرًا إيجابيًا في مستوى التعليم.\n\nنسعى لأن نكون شريكًا موثوقًا في رحلة التفوق الدراسي لكل طالب يسعى لتحقيق أهدافه الأكاديمية.',
        ),
        (
            'our-story',
            'قصتنا',
            'بدأت أكاديمية سنا في عام ٢٠٢١ برؤية بسيطة: جعل التعليم عالي الجودة متاحًا لكل طالب في المملكة العربية السعودية. انطلقنا بفريق صغير من المعلمين المتميزين وشغف كبير لإحداث فرق حقيقي في حياة الطلاب.\n\nعلى مدار السنوات الماضية، نمت الأكاديمية لتصبح واحدة من أبرز المنصات التعليمية في المملكة. اليوم، نفخر بخدمة أكثر من ١٠,٠٠٠ طالب من مختلف المدن السعودية، مع فريق يضم أكثر من ٥٠٠ معلم معتمد متخصصين في جميع المواد الدراسية.\n\nما يميزنا هو التزامنا بالجودة والشفافية. كل معلم في منصتنا يمر بعملية تأهيل صارمة، ونوفر لأولياء الأمور تقارير دورية عن تقدم أبنائهم. نؤمن بأن التعليم الناجح يقوم على الشراكة بين المعلم والطالب وولي الأمر.\n\nنحن فخورون بكوننا جزءًا من رؤية المملكة ٢٠٣٠ في تطوير قطاع التعليم، ونعمل باستمرار على تحسين خدماتنا وتوسيع نطاقنا لنصل إلى كل طالب يحتاج دعمًا دراسيًا.',
        ),
    ]
    for order, (slug, title, content) in enumerate(content_blocks, start=1):
        ContentBlock.objects.update_or_create(
            slug=slug,
            defaults={
                'title': title,
                'content': content,
                'order': order,
                'is_active': True,
            },
        )

    for order, (number, label, icon) in enumerate(
        [
            ('٢٠٢١', 'سنة التأسيس', 'calendar'),
            ('+٥٠٠', 'معلم معتمد', 'user'),
            ('+١٠,٠٠٠', 'طالب مسجل', 'graduation-cap'),
            ('٩٨٪', 'نسبة الرضا', 'star-filled'),
        ],
        start=1,
    ):
        Statistic.objects.update_or_create(
            label=label,
            defaults={
                'number': number,
                'icon': icon,
                'order': order,
                'is_active': True,
            },
        )

    team_members = [
        ('د. أحمد الفهد', 'المدير التنفيذي', 'خبرة ١٥ عامًا في قطاع التعليم، قاد مشاريع تعليمية رقمية ناجحة في المنطقة.'),
        ('م. فاطمة الحربي', 'مديرة المحتوى التعليمي', 'متخصصة في تطوير المناهج الدراسية ومعلمة سابقة في مدارس مرموقة.'),
        ('عمر السبيعي', 'مدير التقنية', 'مهندس برمجيات بخبرة في بناء منصات تعليمية ذكية وقابلة للتوسع.'),
        ('نورة القحطاني', 'مديرة تجربة المستخدم', 'تضمن تجربة مستخدم سلسة ومريحة للطلاب وأولياء الأمور.'),
        ('خالد العتيبي', 'مدير جودة المعلمين', 'يشرف على تأهيل وتقييم المعلمين لضمان أعلى معايير الجودة.'),
        ('سارة المطيري', 'مديرة خدمة العملاء', 'تقود فريق الدعم لضمان رضا كل طالب وولي أمر.'),
    ]
    for order, (name, title, description) in enumerate(team_members, start=1):
        TeamMember.objects.update_or_create(
            name=name,
            defaults={
                'title': title,
                'description': description,
                'order': order,
                'is_active': True,
            },
        )

    for order, (number, label, icon) in enumerate(
        [
            ('+٥٠٠', 'معلم معتمد', 'user'),
            ('+١٠,٠٠٠', 'طالب مسجل', 'graduation-cap'),
            ('+٥٠,٠٠٠', 'حصة مكتملة', 'book'),
            ('٩٨٪', 'نسبة الرضا', 'star-filled'),
        ],
        start=1,
    ):
        Achievement.objects.update_or_create(
            label=label,
            defaults={
                'number': number,
                'icon': icon,
                'order': order,
                'is_active': True,
            },
        )

    Partner.objects.filter(name='شريك تأسيسي').update(is_active=False)
    for order, name in enumerate(
        [
            'جامعة الملك سعود',
            'وزارة التعليم',
            'جامعة الملك عبدالله',
            'مؤسسة الراجحي',
            'شركة جرير',
            'المؤسسة الوطنية',
            'هيئة التعليم',
            'الصندوق التعليمي',
        ],
        start=1,
    ):
        Partner.objects.update_or_create(
            name=name,
            defaults={
                'order': order,
                'is_active': True,
            },
        )

    CTABlock.objects.update_or_create(
        slug='about-cta',
        defaults={
            'heading': 'انضم إلى عائلة أكاديمية سنا',
            'body_text': 'سواء كنت طالبًا يسعى للتفوق أو معلمًا يبحث عن منصة موثوقة، نرحب بانضمامك إلينا.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل معنا',
            'secondary_cta_url': '/contact/',
            'social_proof_text': 'انضم إلى أكثر من ١٠,٠٠٠ طالب حققوا أهدافهم الدراسية معنا',
            'is_active': True,
        },
    )

    steps = [
        'اختر المادة والمرحلة',
        'تصفح المعلمين واختر الأنسب',
        'حدد الموعد المناسب',
        'احضر الحصة أونلاين',
        'تابع تقدمك مع التقارير',
        'حقق التفوق الدراسي',
    ]
    step_descriptions = [
        'حدد المادة الدراسية أو الاختبار الذي تريد التحضير له، واختر المرحلة الدراسية المناسبة. نوفر الرياضيات والعلوم واللغات والقدرات والتحصيلي.',
        'راجع ملفات المعلمين المعتمدين، واطلع على خبراتهم وتقييماتهم وآراء الطلاب السابقين، ثم اختر المعلم الذي يناسب أسلوب تعلمك.',
        'اختر الموعد الذي يناسب جدولك من المواعيد المتاحة. نوفر مرونة كاملة في الجدولة مع إمكانية إعادة الحجز بسهولة.',
        'انضم إلى الحصة من أي مكان عبر منصتنا التفاعلية. حصص مباشرة مع إمكانية التسجيل للمراجعة لاحقًا، ومتابعة فورية من ولي الأمر.',
        'استلم تقارير دورية عن أدائك ونقاط القوة والمجالات التي تحتاج تحسين. متابعة مستمرة لضمان التقدم الفعلي.',
        'مع المتابعة المستمرة والتعلم المخصص، ستلاحظ تحسنًا واضحًا في فهمك للمواد وأدائك في الاختبارات. هدفنا تفوقك.',
    ]
    for order, (title, description) in enumerate(zip(steps, step_descriptions, strict=False), start=1):
        HowItWorksStep.objects.update_or_create(
            step_number=order,
            defaults={
                'title': title,
                'description': description,
                'icon': 'checkmark-circle',
                'order': order,
                'is_active': True,
            },
        )

    why_us_features = [
        ('معلمون معتمدون', 'نخبة من المعلمين الحاصلين على أعلى الشهادات والخبرات في تدريس المناهج السعودية.', 'graduation-cap'),
        ('مواعيد مرنة', 'جدول يناسب وقتك. احجز في الصباح أو المساء، مع إمكانية إعادة الجدولة بسهولة.', 'clock'),
        ('تقارير دورية', 'متابعة مستمرة للأداء مع تقارير تفصيلية للطالب وولي الأمر بعد كل حصة.', 'chart-up'),
        ('حصص مسجلة', 'كل الحصص مسجلة ومتاحة للمراجعة. أعد مشاهدة أي درس في أي وقت تحتاجه.', 'book'),
        ('دعم متواصل', 'فريق دعم متاح للرد على استفساراتك ومساعدتك في أي وقت خلال رحلتك التعليمية.', 'whatsapp'),
        ('مناهج محدثة', 'محتوى متوافق مع أحدث المناهج السعودية، مع تحديثات مستمرة تواكب التغييرات.', 'checkmark-circle'),
    ]
    for order, (title, description, icon) in enumerate(why_us_features, start=1):
        WhyUsFeature.objects.update_or_create(
            title=title,
            defaults={
                'description': description,
                'icon': icon,
                'order': order,
                'is_active': True,
            },
        )

    parent_features = [
        ('تقارير أسبوعية مفصلة', 'استلم تقريرًا عن كل حصة يشمل ما تم إنجازه ونقاط التحسين.', 'core'),
        ('تواصل مباشر مع المعلمين', 'قنوات تواصل مفتوحة لمناقشة أي استفسارات حول سير التعلم.', 'core'),
        ('لوحة متابعة سهلة الاستخدام', 'اطلع على الجدول والحصص القادمة والسابقة من مكان واحد.', 'core'),
        ('إشعارات فورية', 'تنبيهات عند انتهاء الحصة وبدء الواجب.', 'capability'),
        ('تقييم الأداء', 'مؤشرات واضحة عن مستوى الطالب.', 'capability'),
        ('سجل الحضور', 'تاريخ كامل للحصص المحضورة.', 'capability'),
    ]
    for order, (title, description, feature_type) in enumerate(parent_features, start=1):
        ParentFeature.objects.update_or_create(
            title=title,
            feature_type=feature_type,
            defaults={
                'description': description,
                'icon': 'checkmark-circle',
                'order': order,
                'is_active': True,
            },
        )

    testimonials = [
        (
            'سارة المطيري',
            'سم',
            'ثاني ثانوي',
            'رياضيات',
            'كنت أتهرب من الرياضيات تمامًا، وبعد ستة أسابيع من الخطة الفردية أصبحت أتعامل مع الأسئلة بثقة وأحل أسرع بكثير في الاختبارات.',
        ),
        (
            'عبدالله الشعلان',
            'عش',
            'ثالث ثانوي',
            'قدرات',
            'الاختبارات المحاكية والتغذية الراجعة بعد كل محاولة كانت أكثر شيء فرق معي، لأنني أخيرًا عرفت أين أضيّع الوقت وكيف أصلحه.',
        ),
        (
            'نوف الهزاني',
            'نه',
            'أول ثانوي',
            'إنجليزي',
            'أحببت وضوح الواجبات القصيرة بعد كل حصة. لم يعد عندي تشتت، وصرت أتكلم بثقة أكبر في المدرسة وفي الاختبارات الشفوية.',
        ),
    ]
    for order, (student_name, initials, level, subject, quote) in enumerate(testimonials, start=1):
        Testimonial.objects.update_or_create(
            student_name=student_name,
            page='how-it-works',
            defaults={
                'student_initials': initials,
                'level': level,
                'subject': subject,
                'rating': 5,
                'quote': quote,
                'order': order,
                'is_active': True,
                'is_featured': False,
            },
        )

    CTABlock.objects.update_or_create(
        slug='how-it-works-cta',
        defaults={
            'heading': 'جاهز للبدء؟ احجز حصتك الأولى',
            'subheading': 'ابدأ الآن',
            'body_text': 'انضم إلى آلاف الطلاب الذين يحققون نتائج ملموسة معنا. احجز حصة تجريبية مجانية واكتشف الفرق بنفسك.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل عبر الواتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'حصة تجريبية مجانية - بدون التزام',
            'is_active': True,
        },
    )


def unseed_about_content(apps, schema_editor):
    Achievement = apps.get_model('about', 'Achievement')
    ContentBlock = apps.get_model('about', 'ContentBlock')
    HowItWorksStep = apps.get_model('about', 'HowItWorksStep')
    PageContent = apps.get_model('about', 'PageContent')
    ParentFeature = apps.get_model('about', 'ParentFeature')
    Statistic = apps.get_model('about', 'Statistic')
    TeamMember = apps.get_model('about', 'TeamMember')
    WhyUsFeature = apps.get_model('about', 'WhyUsFeature')
    CTABlock = apps.get_model('main', 'CTABlock')
    Partner = apps.get_model('main', 'Partner')
    Testimonial = apps.get_model('main', 'Testimonial')

    Achievement.objects.filter(
        label__in=['معلم معتمد', 'طالب مسجل', 'حصة مكتملة', 'نسبة الرضا']
    ).delete()
    ContentBlock.objects.filter(slug__in=['mission', 'vision', 'our-story']).delete()
    HowItWorksStep.objects.filter(step_number__in=[1, 2, 3, 4, 5, 6]).delete()
    PageContent.objects.filter(slug__in=['about', 'how-it-works']).delete()
    ParentFeature.objects.filter(
        title__in=[
            'تقارير أسبوعية مفصلة',
            'تواصل مباشر مع المعلمين',
            'لوحة متابعة سهلة الاستخدام',
            'إشعارات فورية',
            'تقييم الأداء',
            'سجل الحضور',
        ]
    ).delete()
    Statistic.objects.filter(
        label__in=['سنة التأسيس', 'معلم معتمد', 'طالب مسجل', 'نسبة الرضا']
    ).delete()
    TeamMember.objects.filter(
        name__in=[
            'د. أحمد الفهد',
            'م. فاطمة الحربي',
            'عمر السبيعي',
            'نورة القحطاني',
            'خالد العتيبي',
            'سارة المطيري',
        ]
    ).delete()
    WhyUsFeature.objects.filter(
        title__in=[
            'معلمون معتمدون',
            'مواعيد مرنة',
            'تقارير دورية',
            'حصص مسجلة',
            'دعم متواصل',
            'مناهج محدثة',
        ]
    ).delete()
    CTABlock.objects.filter(slug__in=['about-cta', 'how-it-works-cta']).delete()
    Partner.objects.filter(
        name__in=[
            'جامعة الملك سعود',
            'وزارة التعليم',
            'جامعة الملك عبدالله',
            'مؤسسة الراجحي',
            'شركة جرير',
            'المؤسسة الوطنية',
            'هيئة التعليم',
            'الصندوق التعليمي',
        ]
    ).delete()
    Partner.objects.filter(name='شريك تأسيسي').update(is_active=True)
    Testimonial.objects.filter(
        student_name__in=['سارة المطيري', 'عبدالله الشعلان', 'نوف الهزاني'],
        page='how-it-works',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('main', '0004_seed_homepage_content'),
    ]

    operations = [
        migrations.RunPython(seed_about_content, unseed_about_content),
    ]
