# Generated by Django 6.0.3 on 2026-04-02 18:22

from django.db import migrations


def seed_contact_content(apps, schema_editor):
    ContactFAQ = apps.get_model('contact', 'ContactFAQ')
    ContactPageSettings = apps.get_model('contact', 'ContactPageSettings')
    OperatingHours = apps.get_model('contact', 'OperatingHours')
    WhyChoosePoint = apps.get_model('contact', 'WhyChoosePoint')
    CTABlock = apps.get_model('main', 'CTABlock')
    SiteSettings = apps.get_model('main', 'SiteSettings')

    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            'site_name': 'أكاديمية سنا',
            'phone': '+966 11 400 0000',
            'email': 'info@premiumacademy.sa',
            'whatsapp': '966500000000',
            'address': 'الرياض، المملكة العربية السعودية',
            'google_maps_url': 'https://maps.google.com',
            'site_description': 'منصة تعليمية عربية متخصصة في الدروس الخصوصية والقدرات والتحصيلي.',
        },
    )

    ContactPageSettings.objects.update_or_create(
        pk=1,
        defaults={
            'hero_title': 'تواصل معنا',
            'hero_subtitle': 'نسعد بتواصلك معنا. فريقنا جاهز للإجابة على استفساراتك ومساعدتك في رحلتك التعليمية.',
            'meta_title': 'تواصل معنا | أكاديمية سنا',
            'meta_description': 'تواصل مع فريق أكاديمية سنا واحصل على إجابات سريعة ومساعدة في اختيار المسار التعليمي المناسب.',
        },
    )

    why_choose_points = [
        'معلمون معتمدون بخبرة تزيد عن ٥ سنوات',
        'مرونة في المواعيد تناسب جدولك',
        'تقارير دورية عن تقدم الطالب',
        'حصص تجريبية مجانية قبل الاشتراك',
        'دعم فني متواصل على مدار الساعة',
    ]
    for order, text in enumerate(why_choose_points, start=1):
        WhyChoosePoint.objects.update_or_create(
            text=text,
            defaults={'order': order, 'is_active': True},
        )

    operating_hours = [
        ('السبت – الخميس', '٨ صباحًا – ١٠ مساءً', '* يمكن حجز الحصص في أي وقت من خلال المنصة، ويتوافق مع مواعيد المعلمين المتاحة.'),
        ('الجمعة', 'مغلق', ''),
    ]
    for order, (day_label, time_range, note) in enumerate(operating_hours, start=1):
        OperatingHours.objects.update_or_create(
            day_label=day_label,
            defaults={
                'time_range': time_range,
                'note': note,
                'order': order,
                'is_active': True,
            },
        )

    contact_faqs = [
        ('كيف أتواصل بسرعة؟', 'أسرع طريقة للتواصل هي عبر واتساب على الرقم +966 50 000 0000. فريقنا يرد عادة خلال دقائق خلال ساعات العمل.'),
        ('ما هي أوقات الدعم الفني؟', 'فريق الدعم الفني متاح من السبت إلى الخميس، من الساعة ٨ صباحًا حتى ١٠ مساءً بتوقيت السعودية.'),
        ('هل يمكنني زيارة المقر؟', 'نحن منصة تعليمية رقمية بالكامل، لذا جميع خدماتنا تُقدَّم عن بُعد. إذا كنت ترغب في زيارة مقرنا للتعرف علينا أكثر، يرجى التواصل معنا لحجز موعد مسبق.'),
        ('كم يستغرق الرد على الرسائل؟', 'نسعى للرد على جميع الرسائل خلال ٢٤ ساعة عمل. في معظم الحالات، نرد خلال بضع ساعات فقط. للردود الفورية، ننصح باستخدام واتساب.'),
        ('هل تقدمون استشارات مجانية؟', 'نعم! نقدم حصة تجريبية مجانية لكل طالب جديد، بالإضافة إلى استشارة تعليمية مجانية لتقييم احتياجات الطالب وتقديم الخطة المناسبة.'),
    ]
    for order, (question, answer) in enumerate(contact_faqs, start=1):
        ContactFAQ.objects.update_or_create(
            question=question,
            defaults={
                'answer': answer,
                'order': order,
                'is_active': True,
            },
        )

    CTABlock.objects.update_or_create(
        slug='contact-cta',
        defaults={
            'heading': 'ابدأ رحلتك التعليمية الآن',
            'subheading': 'تواصل معنا',
            'body_text': 'فريقنا جاهز لمساعدتك في اختيار المعلم أو المسار المناسب لك.',
            'primary_cta_text': 'احجز حصة تجريبية',
            'primary_cta_url': '/contact/',
            'secondary_cta_text': 'واتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'رد سريع خلال ساعات العمل',
            'is_active': True,
        },
    )


def unseed_contact_content(apps, schema_editor):
    ContactFAQ = apps.get_model('contact', 'ContactFAQ')
    ContactPageSettings = apps.get_model('contact', 'ContactPageSettings')
    OperatingHours = apps.get_model('contact', 'OperatingHours')
    WhyChoosePoint = apps.get_model('contact', 'WhyChoosePoint')
    CTABlock = apps.get_model('main', 'CTABlock')

    ContactFAQ.objects.filter(
        question__in=[
            'كيف أتواصل بسرعة؟',
            'ما هي أوقات الدعم الفني؟',
            'هل يمكنني زيارة المقر؟',
            'كم يستغرق الرد على الرسائل؟',
            'هل تقدمون استشارات مجانية؟',
        ]
    ).delete()
    ContactPageSettings.objects.filter(pk=1).delete()
    OperatingHours.objects.filter(day_label__in=['السبت – الخميس', 'الجمعة']).delete()
    WhyChoosePoint.objects.filter(
        text__in=[
            'معلمون معتمدون بخبرة تزيد عن ٥ سنوات',
            'مرونة في المواعيد تناسب جدولك',
            'تقارير دورية عن تقدم الطالب',
            'حصص تجريبية مجانية قبل الاشتراك',
            'دعم فني متواصل على مدار الساعة',
        ]
    ).delete()
    CTABlock.objects.filter(slug='contact-cta').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('main', '0004_seed_homepage_content'),
    ]

    operations = [
        migrations.RunPython(seed_contact_content, unseed_contact_content),
    ]
