upstream snaacademy {
    server unix:/run/gunicorn.sock;
}

server {
    listen 80;
    server_name snaacademy.com www.snaacademy.com;

    access_log /var/log/nginx/snaacademy_access.log;
    error_log  /var/log/nginx/snaacademy_error.log;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/premium_academy/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/premium_academy/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
