# Generated by Django 6.0.3 on 2026-04-02 18:12

from datetime import datetime, timezone

from django.db import migrations


def seed_blog_content(apps, schema_editor):
    Author = apps.get_model('blogs', 'Author')
    BlogPageSettings = apps.get_model('blogs', 'BlogPageSettings')
    BlogPost = apps.get_model('blogs', 'BlogPost')
    Category = apps.get_model('blogs', 'Category')
    CTABlock = apps.get_model('main', 'CTABlock')

    BlogPageSettings.objects.update_or_create(
        pk=1,
        defaults={
            'title': 'المدونة',
            'subtitle': 'اكتشف مقالات تعليمية، نصائح دراسية، وأخبار المنصة لمساعدتك على التفوق في رحلتك التعليمية.',
            'description': 'اكتشف مقالات تعليمية، نصائح دراسية، وأخبار المنصة لمساعدتك على التفوق في رحلتك التعليمية.',
            'meta_title': 'المدونة | أكاديمية سنا',
            'meta_description': 'مدونة أكاديمية سنا للمقالات التعليمية والنصائح الدراسية.',
        },
    )

    categories = {
        'تعليم': ('تعليم', 'مقالات تعليمية عامة', 1),
        'نصائح-دراسية': ('نصائح دراسية', 'نصائح عملية للمذاكرة والاختبارات', 2),
        'القدرات-والتحصيلي': ('القدرات والتحصيلي', 'مقالات القدرات والتحصيلي', 3),
        'أخبار-المنصة': ('أخبار المنصة', 'مستجدات المنصة وقصص النجاح', 4),
    }
    category_map = {}
    for slug, (name, description, order) in categories.items():
        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'order': order,
                'is_active': True,
            },
        )
        category_map[slug] = category

    authors = {
        'فاطمة-الحربي': ('م. فاطمة الحربي', 'مديرة المحتوى التعليمي', 'متخصصة في تطوير المناهج الدراسية ومعلمة سابقة في مدارس مرموقة. تتمتع بخبرة ١٢ عامًا في مجال التعليم وتطوير المحتوى التعليمي الرقمي.', 'م.ف', 1),
        'عبدالرحمن-الشمري': ('أ. عبدالرحمن الشمري', 'معلم رياضيات', 'خبير في تبسيط مفاهيم الرياضيات وبناء الخطط الدراسية العلاجية.', 'أ.ع', 2),
        'سارة-العنزي': ('د. سارة العنزي', 'مختصة الفيزياء التعليمية', 'تقدم محتوى يربط الفيزياء بالتطبيق العملي وأساليب الحل السريع.', 'د.س', 3),
        'نورة-القحطاني': ('أ. نورة القحطاني', 'مرشدة دراسية', 'تكتب عن العادات الدراسية الفعالة وبناء الانضباط اليومي للطالب.', 'أ.ن', 4),
        'محمد-الدوسري': ('أ. محمد الدوسري', 'مدرب لغة إنجليزية', 'يركز على مهارات اللغة الإنجليزية العملية والتواصل الأكاديمي.', 'أ.م', 5),
        'فريق-أكاديمية-سنا': ('فريق أكاديمية سنا', 'فريق التحرير', 'فريق داخلي يوثق الأخبار والقصص التعليمية والنجاحات الجديدة في المنصة.', 'ف.س', 6),
    }
    author_map = {}
    for slug, (name, title, bio, initials, order) in authors.items():
        author, _ = Author.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'title': title,
                'bio': bio,
                'initials': initials,
                'photo': '',
                'order': order,
                'is_active': True,
            },
        )
        author_map[slug] = author

    posts = [
        (
            '٥-نصائح-للتفوق-في-اختبار-القدرات',
            '٥ نصائح للتفوق في اختبار القدرات',
            'خمس نصائح مجربة ستساعدك على تحقيق درجة عالية والتفوق في هذا الاختبار الحاسم.',
            'يُعد اختبار القدرات من أهم المعايير التي تعتمد عليها الجامعات السعودية في قبول الطلاب. هذا الاختبار يمكن أن يُحدث فرقًا كبيرًا في مستقبلك الأكاديمي.\n\nافهم طبيعة الاختبار جيدًا، وضع خطة دراسية واقعية، ودرّب نفسك على النماذج السابقة، وراجع المفاهيم الأساسية، واعتن بصحتك النفسية والجسدية قبل الاختبار.',
            'نصائح-دراسية',
            'فاطمة-الحربي',
            'lightbulb',
            5,
            True,
            datetime(2026, 3, 15, 10, 0, tzinfo=timezone.utc),
        ),
        (
            'كيف-تتفوق-في-مادة-الرياضيات',
            'كيف تتفوق في مادة الرياضيات',
            'نصائح عملية واستراتيجيات فعالة لتحسين مستواك في الرياضيات وتحقيق الدرجات العالية.',
            'الرياضيات مادة تراكمية، ولذلك فإن بناء الفهم من الأساسيات ثم التدرب المستمر هو الطريق الأسرع للتفوق.\n\nابدأ بتحديد الفجوات، ثم راجع القواعد الأساسية، وبعدها انتقل إلى حل تدريجي للمسائل مع متابعة الأخطاء المتكررة.',
            'تعليم',
            'عبدالرحمن-الشمري',
            'calculator',
            4,
            False,
            datetime(2026, 3, 12, 10, 0, tzinfo=timezone.utc),
        ),
        (
            'أسرار-النجاح-في-مادة-الفيزياء',
            'أسرار النجاح في مادة الفيزياء',
            'دليل شامل لفهم مفاهيم الفيزياء الصعبة وتطبيقها في حل المسائل المعقدة.',
            'النجاح في الفيزياء لا يعتمد على الحفظ فقط، بل على فهم العلاقات بين المفاهيم والتدرب على تحويل السؤال إلى خطوات منطقية.\n\nكلما تدربت على قراءة المعطيات وربطها بالقانون المناسب، أصبح الحل أكثر سرعة وثباتًا.',
            'تعليم',
            'سارة-العنزي',
            'atom',
            4,
            False,
            datetime(2026, 3, 10, 10, 0, tzinfo=timezone.utc),
        ),
        (
            'التحصيلي-خطة-دراسية-شاملة',
            'التحصيلي: خطة دراسية شاملة',
            'خطة دراسية مفصلة للتحضير لاختبار التحصيلي مع جدول زمني ومصادر موصى بها.',
            'التحصيلي يحتاج إلى توزيع ذكي للمراجعة بين المواد العلمية، مع اختبارات قصيرة دورية تكشف نقاط الضعف مبكرًا.\n\nقسّم الأسابيع بين التأسيس والمراجعة والمحاكاة، ولا تترك المادة الأضعف إلى نهاية الخطة.',
            'القدرات-والتحصيلي',
            'فاطمة-الحربي',
            'brain',
            6,
            False,
            datetime(2026, 3, 8, 10, 0, tzinfo=timezone.utc),
        ),
        (
            '١٠-عادات-للطلاب-المتفوقين',
            '١٠ عادات للطلاب المتفوقين',
            'تعرف على العادات اليومية التي يتبعها الطلاب المتفوقون وكيف يمكنك تطبيقها.',
            'التفوق لا يأتي من جلسات دراسة عشوائية، بل من عادات صغيرة متكررة مثل التخطيط اليومي، والمراجعة القصيرة، وتثبيت مواعيد النوم، وتقليل المشتتات.\n\nحين تصبح هذه السلوكيات جزءًا من يومك، تتحسن نتائجك بشكل طبيعي ومستمر.',
            'نصائح-دراسية',
            'نورة-القحطاني',
            'pen',
            4,
            False,
            datetime(2026, 3, 5, 10, 0, tzinfo=timezone.utc),
        ),
        (
            'تحسين-مهارات-اللغة-الإنجليزية',
            'تحسين مهارات اللغة الإنجليزية',
            'طرق فعالة لتطوير مهارات القراءة والكتابة والمحادثة في اللغة الإنجليزية.',
            'تحسين اللغة الإنجليزية يحتاج إلى مزيج من التكرار والتطبيق. القراءة اليومية القصيرة، والاستماع المنتظم، والتحدث دون خوف من الخطأ، كلها عناصر مهمة.\n\nالأهم أن يكون التدريب مستمرًا ومتناسبًا مع مستوى الطالب الحالي.',
            'تعليم',
            'محمد-الدوسري',
            'globe',
            5,
            False,
            datetime(2026, 3, 3, 10, 0, tzinfo=timezone.utc),
        ),
        (
            'قصص-نجاح-طلابنا-المتفوقين',
            'قصص نجاح طلابنا المتفوقين',
            'نحتفي بطلابنا الذين حققوا نتائج استثنائية مع أكاديمية سنا هذا العام.',
            'وراء كل نتيجة كبيرة خطة دقيقة ومعلم مناسب ومتابعة مستمرة. في هذا المقال نسلط الضوء على قصص حقيقية لطلاب حققوا نقلات واضحة في درجاتهم وثقتهم بأنفسهم.\n\nهذه القصص توضح كيف تتحول المتابعة المنتظمة إلى نتائج ملموسة.',
            'أخبار-المنصة',
            'فريق-أكاديمية-سنا',
            'trophy',
            3,
            False,
            datetime(2026, 3, 1, 10, 0, tzinfo=timezone.utc),
        ),
    ]

    for slug, title, excerpt, content, category_slug, author_slug, icon, read_time_minutes, is_featured, published_date in posts:
        BlogPost.objects.update_or_create(
            slug=slug,
            defaults={
                'title': title,
                'excerpt': excerpt,
                'content': content,
                'featured_image': '',
                'category': category_map[category_slug],
                'author': author_map[author_slug],
                'icon': icon,
                'read_time_minutes': read_time_minutes,
                'status': 'published',
                'is_featured': is_featured,
                'published_date': published_date,
                'meta_title': f'{title} | أكاديمية سنا',
                'meta_description': excerpt,
            },
        )

    CTABlock.objects.update_or_create(
        slug='blog-cta',
        defaults={
            'heading': 'هل أنت مستعد للتفوق؟',
            'subheading': 'ابدأ الآن',
            'body_text': 'انضم إلى آلاف الطلاب الذين حققوا أهدافهم الدراسية مع أكاديمية سنا.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل معنا',
            'secondary_cta_url': '/contact/',
            'social_proof_text': '',
            'is_active': True,
        },
    )
    CTABlock.objects.update_or_create(
        slug='blog-post-cta',
        defaults={
            'heading': 'هل تريد تحقيق التفوق في اختبار القدرات؟',
            'subheading': 'ابدأ الآن',
            'body_text': 'انضم إلى أكاديمية سنا واحصل على أفضل التحضيرات مع معلمين متخصصين.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'احجز حصة تجريبية مجانية',
            'secondary_cta_url': '/contact/',
            'social_proof_text': '',
            'is_active': True,
        },
    )


def unseed_blog_content(apps, schema_editor):
    Author = apps.get_model('blogs', 'Author')
    BlogPageSettings = apps.get_model('blogs', 'BlogPageSettings')
    BlogPost = apps.get_model('blogs', 'BlogPost')
    Category = apps.get_model('blogs', 'Category')
    CTABlock = apps.get_model('main', 'CTABlock')

    BlogPost.objects.filter(
        slug__in=[
            '٥-نصائح-للتفوق-في-اختبار-القدرات',
            'كيف-تتفوق-في-مادة-الرياضيات',
            'أسرار-النجاح-في-مادة-الفيزياء',
            'التحصيلي-خطة-دراسية-شاملة',
            '١٠-عادات-للطلاب-المتفوقين',
            'تحسين-مهارات-اللغة-الإنجليزية',
            'قصص-نجاح-طلابنا-المتفوقين',
        ]
    ).delete()
    Author.objects.filter(
        slug__in=[
            'فاطمة-الحربي',
            'عبدالرحمن-الشمري',
            'سارة-العنزي',
            'نورة-القحطاني',
            'محمد-الدوسري',
            'فريق-أكاديمية-سنا',
        ]
    ).delete()
    Category.objects.filter(
        slug__in=[
            'تعليم',
            'نصائح-دراسية',
            'القدرات-والتحصيلي',
            'أخبار-المنصة',
        ]
    ).delete()
    BlogPageSettings.objects.filter(pk=1).delete()
    CTABlock.objects.filter(slug__in=['blog-cta', 'blog-post-cta']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('main', '0004_seed_homepage_content'),
    ]

    operations = [
        migrations.RunPython(seed_blog_content, unseed_blog_content),
    ]
