# Generated by Django 6.0.3 on 2026-04-02 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_seed_subject_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='teachers/')),
            ],
            options={
                'verbose_name': 'Teacher Page Settings',
                'verbose_name_plural': 'Teacher Page Settings',
            },
        ),
        migrations.CreateModel(
            name='TeacherStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('full_bio', models.TextField()),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('experience_description', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('platform_years', models.PositiveSmallIntegerField(default=0)),
                ('success_rate', models.PositiveSmallIntegerField(default=98)),
                ('session_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('booking_cta_text', models.CharField(blank=True, default='احجز حصة', max_length=50)),
                ('booking_cta_url', models.CharField(blank=True, default='/contact/', max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('primary_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='course.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day_of_week', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teacher.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher availability',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='teacher.teacher')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(max_length=100)),
                ('student_initials', models.CharField(blank=True, max_length=10)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField()),
                ('review_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teacher.teacher')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=200)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_specializations', to='course.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='teacher.teacher')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
