# Generated by Django 6.0.3 on 2026-04-02 18:00

from django.db import migrations


def seed_teacher_content(apps, schema_editor):
    Subject = apps.get_model('course', 'Subject')
    CTABlock = apps.get_model('main', 'CTABlock')
    Testimonial = apps.get_model('main', 'Testimonial')
    Teacher = apps.get_model('teacher', 'Teacher')
    TeacherAvailability = apps.get_model('teacher', 'TeacherAvailability')
    TeacherFeature = apps.get_model('teacher', 'TeacherFeature')
    TeacherPageSettings = apps.get_model('teacher', 'TeacherPageSettings')
    TeacherReview = apps.get_model('teacher', 'TeacherReview')
    TeacherSpecialization = apps.get_model('teacher', 'TeacherSpecialization')
    TeacherStat = apps.get_model('teacher', 'TeacherStat')

    subject_map = {}
    required_subjects = [
        ('الرياضيات', 'الرياضيات', 'تأسيس ومتابعة في الرياضيات'),
        ('الفيزياء', 'الفيزياء', 'شرح وتدريب مكثف في الفيزياء'),
        ('الكيمياء', 'الكيمياء', 'تبسيط مفاهيم الكيمياء والتجارب'),
        ('اللغة-الإنجليزية', 'اللغة الإنجليزية', 'مهارات اللغة الإنجليزية والاختبارات'),
        ('اللغة-العربية', 'اللغة العربية', 'مهارات القراءة والكتابة والقواعد'),
        ('الأحياء', 'الأحياء', 'شرح مفاهيم الأحياء بشكل تطبيقي'),
        ('القدرات', 'القدرات', 'استعداد شامل لاختبار القدرات'),
        ('التحصيلي', 'التحصيلي', 'مراجعة واختبارات للتحصيلي'),
    ]
    for index, (slug, name, description) in enumerate(required_subjects, start=1):
        subject, _ = Subject.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'icon': '',
                'order': index,
                'is_active': True,
            },
        )
        subject_map[slug] = subject

    TeacherPageSettings.objects.update_or_create(
        pk=1,
        defaults={
            'hero_title': 'نخبة تعليمية تجمع الخبرة والأسلوب الواضح',
            'hero_subtitle': 'معلمونا حاصلون على أعلى الشهادات ويمتلكون سنوات من الخبرة في تدريس المناهج السعودية والقدرات والتحصيلي. اختر المعلم الأنسب لاحتياجك وابدأ رحلتك التعليمية.',
            'hero_image': '',
            'meta_title': 'المعلمون | أكاديمية سنا',
            'meta_description': 'تعرّف على معلمي أكاديمية سنا واختر الملف الأنسب لهدفك الدراسي.',
        },
    )

    stats = [
        ('+٥٠٠', 'معلمون معتمدون', 'متخصصون في جميع المواد'),
        ('٤.٨', 'متوسط التقييم', 'من ٥ نجوم'),
        ('+٥٠,٠٠٠', 'إجمالي الحصص', 'حصة مكتملة بنجاح'),
        ('٩٨٪', 'نسبة الرضا', 'رضا الطلاب وأولياء الأمور'),
    ]
    for order, (number, label, description) in enumerate(stats, start=1):
        TeacherStat.objects.update_or_create(
            label=label,
            defaults={
                'number': number,
                'description': description,
                'icon': '',
                'order': order,
                'is_active': True,
            },
        )

    teachers = [
        {
            'slug': 'عبدالرحمن-الشمري',
            'initials': 'رش',
            'name': 'أ. عبدالرحمن الشمري',
            'subject_slug': 'الرياضيات',
            'title': 'معلم رياضيات متخصص',
            'short_bio': 'معلم رياضيات بخبرة تمتد لعشر سنوات في المتوسط والثانوي.',
            'full_bio': 'معلم رياضيات متخصص مع خبرة تمتد لعشر سنوات في تدريس المناهج السعودية. حاصل على بكالوريوس في الرياضيات من جامعة الملك سعود، وماجستير في المناهج وطرق التدريس.\n\nأسلوبي يعتمد على تبسيط المفاهيم المعقدة وربطها بالحياة اليومية، مع التركيز على بناء الثقة الرياضية لدى الطالب. أؤمن أن كل طالب قادر على التفوق مع الأسلوب المناسب والمتابعة المستمرة.',
            'qualifications': 'بكالوريوس في الرياضيات من جامعة الملك سعود\nماجستير في المناهج وطرق التدريس',
            'experience_years': 10,
            'experience_description': 'متوسط وثانوي',
            'rating': '4.9',
            'student_count': 230,
            'completed_sessions': 1500,
            'platform_years': 3,
            'success_rate': 98,
            'session_rate': '150.00',
            'whatsapp_number': '966500000000',
            'is_featured': True,
            'order': 1,
        },
        {
            'slug': 'سارة-خالد',
            'initials': 'سك',
            'name': 'أ. سارة خالد',
            'subject_slug': 'اللغة-الإنجليزية',
            'title': 'معلمة لغة إنجليزية',
            'short_bio': 'تؤسس اللغة الإنجليزية للابتدائي والمتوسط بخطة متدرجة.',
            'full_bio': 'معلمة لغة إنجليزية تركز على بناء المهارات الأساسية والمحادثة والثقة في الاختبارات المدرسية.',
            'qualifications': 'بكالوريوس لغة إنجليزية',
            'experience_years': 8,
            'experience_description': 'ابتدائي ومتوسط',
            'rating': '4.8',
            'student_count': 185,
            'completed_sessions': 1210,
            'platform_years': 2,
            'success_rate': 97,
            'session_rate': '145.00',
            'whatsapp_number': '966500000000',
            'is_featured': True,
            'order': 2,
        },
        {
            'slug': 'فاطمة-العتيبي',
            'initials': 'فع',
            'name': 'د. فاطمة العتيبي',
            'subject_slug': 'الكيمياء',
            'title': 'معلمة كيمياء للمسارات الثانوية',
            'short_bio': 'تجمع بين الشرح النظري والتطبيق العملي في الكيمياء.',
            'full_bio': 'معلمة كيمياء خبيرة في تبسيط المفاهيم العلمية وربطها بالاختبارات العملية والتحصيلية.',
            'qualifications': 'دكتوراه في الكيمياء',
            'experience_years': 12,
            'experience_description': 'ثانوي ومسارات',
            'rating': '4.9',
            'student_count': 260,
            'completed_sessions': 1840,
            'platform_years': 3,
            'success_rate': 98,
            'session_rate': '160.00',
            'whatsapp_number': '966500000000',
            'is_featured': True,
            'order': 3,
        },
        {
            'slug': 'محمد-العمري',
            'initials': 'مع',
            'name': 'أ. محمد العمري',
            'subject_slug': 'الفيزياء',
            'title': 'معلم فيزياء للثانوي',
            'short_bio': 'متخصص في الفيزياء وشرح المسائل المركبة بوضوح.',
            'full_bio': 'معلم فيزياء يهتم بتثبيت الفهم قبل التدريب المكثف على المسائل والاختبارات.',
            'qualifications': 'بكالوريوس فيزياء',
            'experience_years': 9,
            'experience_description': 'ثانوي',
            'rating': '4.7',
            'student_count': 172,
            'completed_sessions': 1090,
            'platform_years': 3,
            'success_rate': 96,
            'session_rate': '140.00',
            'whatsapp_number': '966500000000',
            'is_featured': True,
            'order': 4,
        },
        {
            'slug': 'نورة-الفهد',
            'initials': 'نف',
            'name': 'أ. نورة الفهد',
            'subject_slug': 'الأحياء',
            'title': 'معلمة أحياء',
            'short_bio': 'تشرح الأحياء بأسلوب بصري وربط عملي سريع.',
            'full_bio': 'معلمة أحياء تركّز على الفهم البصري والملخصات العملية قبل الاختبارات.',
            'qualifications': 'بكالوريوس أحياء',
            'experience_years': 7,
            'experience_description': 'ثانوي',
            'rating': '4.8',
            'student_count': 149,
            'completed_sessions': 980,
            'platform_years': 2,
            'success_rate': 97,
            'session_rate': '135.00',
            'whatsapp_number': '966500000000',
            'is_featured': False,
            'order': 5,
        },
        {
            'slug': 'ليان-الحربي',
            'initials': 'له',
            'name': 'أ. ليان الحربي',
            'subject_slug': 'اللغة-العربية',
            'title': 'معلمة لغة عربية',
            'short_bio': 'متخصصة في القراءة والكتابة والقواعد للمراحل العليا.',
            'full_bio': 'معلمة لغة عربية تجمع بين تأسيس المهارات اللغوية والمراجعات المركزة للاختبارات.',
            'qualifications': 'بكالوريوس لغة عربية',
            'experience_years': 11,
            'experience_description': 'متوسط وثانوي',
            'rating': '4.9',
            'student_count': 214,
            'completed_sessions': 1620,
            'platform_years': 3,
            'success_rate': 98,
            'session_rate': '150.00',
            'whatsapp_number': '966500000000',
            'is_featured': False,
            'order': 6,
        },
        {
            'slug': 'طارق-السبيعي',
            'initials': 'طا',
            'name': 'أ. طارق السبيعي',
            'subject_slug': 'القدرات',
            'title': 'مدرب قدرات كمي ولفظي',
            'short_bio': 'يبني خططًا تدريبية دقيقة لاختبار القدرات.',
            'full_bio': 'مدرب قدرات يوازن بين السرعة والدقة ويستخدم اختبارات محاكية وتقارير تحليلية.',
            'qualifications': 'مدرب معتمد في اختبارات القدرات',
            'experience_years': 13,
            'experience_description': 'كمي ولفظي',
            'rating': '5.0',
            'student_count': 310,
            'completed_sessions': 2260,
            'platform_years': 4,
            'success_rate': 99,
            'session_rate': '175.00',
            'whatsapp_number': '966500000000',
            'is_featured': False,
            'order': 7,
        },
        {
            'slug': 'ياسر-البقمي',
            'initials': 'يب',
            'name': 'أ. ياسر البقمي',
            'subject_slug': 'التحصيلي',
            'title': 'مدرب تحصيلي علمي وأدبي',
            'short_bio': 'يركز على المراجعات النهائية واختبارات التحصيلي.',
            'full_bio': 'مدرب تحصيلي يدمج المراجعات المكثفة مع اختبارات قصيرة وخطط مذاكرة أسبوعية.',
            'qualifications': 'مدرب تحصيلي معتمد',
            'experience_years': 9,
            'experience_description': 'علمي وأدبي',
            'rating': '4.8',
            'student_count': 205,
            'completed_sessions': 1430,
            'platform_years': 3,
            'success_rate': 97,
            'session_rate': '155.00',
            'whatsapp_number': '966500000000',
            'is_featured': False,
            'order': 8,
        },
    ]

    teacher_map = {}
    for teacher_data in teachers:
        teacher, _ = Teacher.objects.update_or_create(
            slug=teacher_data['slug'],
            defaults={
                'initials': teacher_data['initials'],
                'name': teacher_data['name'],
                'primary_subject': subject_map[teacher_data['subject_slug']],
                'title': teacher_data['title'],
                'short_bio': teacher_data['short_bio'],
                'full_bio': teacher_data['full_bio'],
                'qualifications': teacher_data['qualifications'],
                'experience_years': teacher_data['experience_years'],
                'experience_description': teacher_data['experience_description'],
                'rating': teacher_data['rating'],
                'student_count': teacher_data['student_count'],
                'completed_sessions': teacher_data['completed_sessions'],
                'platform_years': teacher_data['platform_years'],
                'success_rate': teacher_data['success_rate'],
                'session_rate': teacher_data['session_rate'],
                'photo': '',
                'booking_cta_text': 'احجز حصة',
                'booking_cta_url': '/contact/',
                'whatsapp_number': teacher_data['whatsapp_number'],
                'is_active': True,
                'is_featured': teacher_data['is_featured'],
                'order': teacher_data['order'],
                'meta_title': f"{teacher_data['name']} | أكاديمية سنا",
                'meta_description': f"ملف {teacher_data['name']} وتخصصه في {subject_map[teacher_data['subject_slug']].name}.",
            },
        )
        teacher_map[teacher_data['slug']] = teacher

    abdulrahman = teacher_map['عبدالرحمن-الشمري']
    TeacherFeature.objects.update_or_create(
        teacher=abdulrahman,
        text='حصص مسجلة متاحة',
        defaults={'order': 1, 'is_active': True},
    )
    TeacherFeature.objects.update_or_create(
        teacher=abdulrahman,
        text='تقارير أسبوعية',
        defaults={'order': 2, 'is_active': True},
    )
    TeacherFeature.objects.update_or_create(
        teacher=abdulrahman,
        text='مرونة في المواعيد',
        defaults={'order': 3, 'is_active': True},
    )

    specializations = [
        ('الرياضيات', 'الرياضيات — متوسط', 'أول، ثاني، ثالث متوسط'),
        ('الرياضيات', 'الرياضيات — ثانوي', 'أول، ثاني، ثالث ثانوي'),
        ('الفيزياء', 'الفيزياء — ثانوي', 'أول، ثاني، ثالث ثانوي'),
    ]
    for order, (subject_slug, label, grade_level) in enumerate(specializations, start=1):
        TeacherSpecialization.objects.update_or_create(
            teacher=abdulrahman,
            label=label,
            defaults={
                'subject': subject_map[subject_slug],
                'grade_level': grade_level,
                'order': order,
                'is_active': True,
            },
        )

    reviews = [
        ('سارة المطيري', 'سم', 'ثاني ثانوي', 'الرياضيات', 5, 'كنت أتهرب من الرياضيات تمامًا، وبعد ستة أسابيع من الخطة الفردية أصبحت أتعامل مع الأسئلة بثقة وأحل أسرع بكثير في الاختبارات. أستاذ عبدالرحمن يعرف كيف يوصل المعلومة.', '2026-03-15'),
        ('عبدالله الشعلان', 'عش', 'ثالث ثانوي', 'الرياضيات', 5, 'أسلوبه في الشرح ممتاز جدًا، يفصّل الخطوات ويكرر النقاط المهمة حتى تتأكد من الفهم. وفر لي خطط مراجعة قبل الاختبارات النهائية ساعدتني كثيرًا.', '2026-03-10'),
        ('نوف الهزاني', 'نه', 'أول ثانوي', 'الرياضيات', 5, 'أحب التمارين التفاعلية والاختبارات القصيرة بعد كل درس. أسلوب المتابعة يجعلني محافظة على مستواي ولا أتراجع.', '2026-03-05'),
        ('رهف لافي', 'رل', 'ثالث متوسط', 'الرياضيات', 5, 'والدتي كانت تتابع التقارير الأسبوعية وتشعر أن كل شيء تحت السيطرة. المعلم يعطي تغذية راجعة واضحة وينبهني للنقاط التي أحتاج مراجعتها.', '2026-02-28'),
    ]
    for order, (student_name, initials, level, subject, rating, quote, review_date) in enumerate(reviews, start=1):
        TeacherReview.objects.update_or_create(
            teacher=abdulrahman,
            student_name=student_name,
            defaults={
                'student_initials': initials,
                'level': level,
                'subject': subject,
                'rating': rating,
                'quote': quote,
                'review_date': review_date,
                'order': order,
                'is_active': True,
            },
        )

    availability_slots = [
        ('السبت', '16:00:00', '22:00:00'),
        ('الأحد', '16:00:00', '22:00:00'),
        ('الاثنين', '16:00:00', '22:00:00'),
        ('الثلاثاء', '16:00:00', '22:00:00'),
    ]
    for order, (day_of_week, start_time, end_time) in enumerate(availability_slots, start=1):
        TeacherAvailability.objects.update_or_create(
            teacher=abdulrahman,
            day_of_week=day_of_week,
            defaults={
                'start_time': start_time,
                'end_time': end_time,
                'note': '',
                'order': order,
                'is_active': True,
            },
        )

    teacher_testimonials = [
        ('سارة المطيري', 'سم', 'ثاني ثانوي', 'رياضيات', 'كنت أتهرب من الرياضيات تمامًا، وبعد ستة أسابيع من الخطة الفردية أصبحت أتعامل مع الأسئلة بثقة وأحل أسرع بكثير في الاختبارات.'),
        ('عبدالله الشعلان', 'عش', 'ثالث ثانوي', 'قدرات', 'الاختبارات المحاكية والتغذية الراجعة بعد كل محاولة كانت أكثر شيء فرق معي، لأنني عرفت أين أضيّع الوقت وكيف أصلحه.'),
        ('نوف الهزاني', 'نه', 'أول ثانوي', 'إنجليزي', 'أحببت وضوح الواجبات القصيرة بعد كل حصة. لم يعد عندي تشتت، وصرت أتكلم بثقة أكبر في المدرسة.'),
        ('رهف لافي', 'رل', 'ثاني متوسط', 'علوم', 'المعلمة كانت تعرف كيف تبسط الدرس وتربطه بأمثلة سهلة. والدتي كانت تتابع التقرير الأسبوعي وتشعر أن كل شيء تحت السيطرة.'),
    ]
    for order, (student_name, initials, level, subject, quote) in enumerate(teacher_testimonials, start=1):
        Testimonial.objects.update_or_create(
            student_name=student_name,
            page='teachers',
            defaults={
                'student_initials': initials,
                'level': level,
                'subject': subject,
                'rating': 5,
                'quote': quote,
                'order': order,
                'is_active': True,
                'is_featured': order == 1,
            },
        )

    CTABlock.objects.update_or_create(
        slug='teachers-cta',
        defaults={
            'heading': 'اختر معلمك وابدأ رحلة التفوق',
            'subheading': 'ابدأ الآن',
            'body_text': 'انضم إلى آلاف الطلاب الذين حققوا نتائج ملموسة مع معلمينا. اختر المادة والمعلم المناسب واحجز حصتك الأولى اليوم.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل عبر الواتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'انضم إلى أكثر من ١٠,٠٠٠ طالب يتعلمون معنا',
            'is_active': True,
        },
    )
    CTABlock.objects.update_or_create(
        slug='teacher-profile-cta',
        defaults={
            'heading': 'ابدأ رحلتك التعليمية مع أ. عبدالرحمن',
            'subheading': 'احجز الآن',
            'body_text': 'احجز حصتك الأولى اليوم واكتشف الفرق مع تعلم مخصص يناسب احتياجاتك وأهدافك الدراسية.',
            'primary_cta_text': 'احجز حصتك الأولى',
            'primary_cta_url': '/contact/',
            'secondary_cta_text': 'تواصل عبر الواتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'حصة تجريبية متاحة — استمتع بتجربة تعليمية مميزة',
            'is_active': True,
        },
    )


def unseed_teacher_content(apps, schema_editor):
    CTABlock = apps.get_model('main', 'CTABlock')
    Testimonial = apps.get_model('main', 'Testimonial')
    Teacher = apps.get_model('teacher', 'Teacher')
    TeacherPageSettings = apps.get_model('teacher', 'TeacherPageSettings')
    TeacherStat = apps.get_model('teacher', 'TeacherStat')

    Teacher.objects.filter(
        slug__in=[
            'عبدالرحمن-الشمري',
            'سارة-خالد',
            'فاطمة-العتيبي',
            'محمد-العمري',
            'نورة-الفهد',
            'ليان-الحربي',
            'طارق-السبيعي',
            'ياسر-البقمي',
        ]
    ).delete()
    TeacherStat.objects.filter(
        label__in=['معلمون معتمدون', 'متوسط التقييم', 'إجمالي الحصص', 'نسبة الرضا']
    ).delete()
    TeacherPageSettings.objects.filter(pk=1).delete()
    Testimonial.objects.filter(
        page='teachers',
        student_name__in=['سارة المطيري', 'عبدالله الشعلان', 'نوف الهزاني', 'رهف لافي'],
    ).delete()
    CTABlock.objects.filter(slug__in=['teachers-cta', 'teacher-profile-cta']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_homepage_content'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_teacher_content, unseed_teacher_content),
    ]
