# Generated by Django 6.0.3 on 2026-04-02 23:29

import apps.teacher.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_seed_teacher_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('specialization', models.CharField(max_length=200, verbose_name='التخصص')),
                ('experience', models.CharField(choices=[('less_1', 'أقل من سنة'), ('1_3', 'من 1 إلى 3 سنوات'), ('3_5', 'من 3 إلى 5 سنوات'), ('5_10', 'من 5 إلى 10 سنوات'), ('more_10', 'أكثر من 10 سنوات')], default='1_3', max_length=20, verbose_name='سنوات الخبرة')),
                ('courses', models.TextField(help_text='اذكر الكورسات أو المواد التي تستطيع تدريسها، سطر لكل كورس.', verbose_name='الكورسات التي يمكنك تدريسها')),
                ('description', models.TextField(help_text='أخبرنا عن نفسك وخبرتك التعليمية.', verbose_name='نبذة عنك')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('reviewing', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
            ],
            options={
                'verbose_name': 'طلب انضمام معلم',
                'verbose_name_plural': 'طلبات انضمام المعلمين',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('certificate', 'شهادة'), ('video', 'مقطع فيديو'), ('screenshot', 'لقطة شاشة'), ('cv', 'السيرة الذاتية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المرفق')),
                ('file', models.FileField(upload_to=apps.teacher.models._application_attachment_path, verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='teacher.teacherapplication', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
    ]
