# Generated by Django 6.0.3 on 2026-04-02 17:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTABlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('primary_cta_text', models.CharField(blank=True, max_length=50)),
                ('primary_cta_url', models.CharField(blank=True, max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=200)),
                ('social_proof_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('pricing', 'Pricing'), ('teachers', 'Teachers'), ('scheduling', 'Scheduling'), ('platform', 'Platform')], max_length=20)),
                ('show_on_homepage', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Page metadata',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Sana Academy', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('logo_white', models.ImageField(blank=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('google_maps_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=200)),
                ('accreditation_text', models.TextField(blank=True)),
                ('accreditation_badge', models.ImageField(blank=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(max_length=100)),
                ('student_initials', models.CharField(max_length=10)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField()),
                ('page', models.CharField(choices=[('homepage', 'Homepage'), ('teachers', 'Teachers'), ('pricing', 'Pricing'), ('how-it-works', 'How It Works')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('telegram', 'Telegram')], max_length=30)),
                ('url', models.URLField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='main.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
