# Generated by Django 6.0.3 on 2026-04-02 17:23

from django.db import migrations


def seed_main_foundations(apps, schema_editor):
    SiteSettings = apps.get_model('main', 'SiteSettings')
    SocialLink = apps.get_model('main', 'SocialLink')
    CTABlock = apps.get_model('main', 'CTABlock')
    FAQ = apps.get_model('main', 'FAQ')
    PageMeta = apps.get_model('main', 'PageMeta')
    RelatedLink = apps.get_model('main', 'RelatedLink')
    LegalPage = apps.get_model('main', 'LegalPage')
    Partner = apps.get_model('main', 'Partner')
    Testimonial = apps.get_model('main', 'Testimonial')

    site_settings, _ = SiteSettings.objects.get_or_create(
        pk=1,
        defaults={
            'site_name': 'أكاديمية سنا',
            'site_description': 'منصة تعليمية عربية متميزة للتدريس الخصوصي والاستعداد للاختبارات.',
            'phone': '+966500000000',
            'email': 'info@sanaacademy.test',
            'whatsapp': '+966500000000',
            'address': 'الرياض، المملكة العربية السعودية',
            'copyright_text': '© أكاديمية سنا. جميع الحقوق محفوظة.',
        },
    )

    SocialLink.objects.get_or_create(
        site_settings=site_settings,
        platform='whatsapp',
        defaults={
            'url': 'https://wa.me/966500000000',
            'order': 1,
            'is_active': True,
        },
    )

    cta_blocks = [
        ('homepage-cta', 'ابدأ رحلتك التعليمية اليوم'),
        ('about-cta', 'تعرف على فريق أكاديمية سنا'),
        ('teachers-cta', 'اختر المعلم المناسب لك'),
        ('teacher-profile-cta', 'احجز حصتك الأولى الآن'),
        ('how-it-works-cta', 'شاهد كيف تبدأ بسهولة'),
        ('pricing-cta', 'اختر الباقة المناسبة لك'),
        ('blog-cta', 'استكشف أحدث المقالات التعليمية'),
        ('blog-post-cta', 'ابدأ خطتك الدراسية معنا'),
    ]
    for index, (slug, heading) in enumerate(cta_blocks, start=1):
        CTABlock.objects.get_or_create(
            slug=slug,
            defaults={
                'heading': heading,
                'subheading': 'تجهيز تأسيسي قابل للتخصيص خلال مراحل التنفيذ القادمة.',
                'primary_cta_text': 'ابدأ الآن',
                'primary_cta_url': '/contact/',
                'secondary_cta_text': 'تصفح المعلمين',
                'secondary_cta_url': '/teachers/',
                'social_proof_text': f'كتلة CTA تأسيسية رقم {index}',
                'is_active': True,
            },
        )

    for slug, title in (
        ('home', 'أكاديمية سنا | الصفحة الرئيسية'),
        ('faq', 'الأسئلة الشائعة | أكاديمية سنا'),
    ):
        PageMeta.objects.get_or_create(
            slug=slug,
            defaults={
                'meta_title': title,
                'meta_description': 'بيانات وصفية تأسيسية سيتم تحديثها مع ربط الصفحات الديناميكية.',
                'is_active': True,
            },
        )

    FAQ.objects.get_or_create(
        question='كيف أبدأ التسجيل في أكاديمية سنا؟',
        defaults={
            'answer': 'يمكنك إرسال طلبك عبر صفحة التواصل وسيقوم الفريق بالتواصل معك لتحديد المسار المناسب.',
            'category': 'general',
            'order': 1,
            'is_active': True,
            'show_on_homepage': True,
        },
    )

    related_links = [
        ('اطلع على الباقات', '/pricing/'),
        ('تواصل مع الفريق', '/contact/'),
        ('تصفح المدونة', '/blog/'),
    ]
    for index, (title, url) in enumerate(related_links, start=1):
        RelatedLink.objects.get_or_create(
            title=title,
            defaults={
                'description': 'رابط تأسيسي مساعد ضمن محتوى الأسئلة الشائعة.',
                'url': url,
                'order': index,
                'is_active': True,
            },
        )

    for slug, title in (
        ('privacy', 'سياسة الخصوصية'),
        ('terms', 'الشروط والأحكام'),
    ):
        LegalPage.objects.get_or_create(
            slug=slug,
            defaults={
                'title': title,
                'content': f'محتوى تأسيسي لصفحة {title} سيتم استبداله بالنص النهائي أثناء مرحلة الصفحات القانونية.',
                'meta_title': f'{title} | أكاديمية سنا',
                'meta_description': 'صفحة قانونية تأسيسية ضمن إعدادات المرحلة الثانية.',
            },
        )

    Partner.objects.get_or_create(
        name='شريك تأسيسي',
        defaults={
            'logo': 'partners/foundation-partner.png',
            'url': 'https://example.com',
            'order': 1,
            'is_active': True,
        },
    )

    Testimonial.objects.get_or_create(
        student_name='طالب تجريبي',
        page='homepage',
        defaults={
            'student_initials': 'ط.ت',
            'level': 'مرحلة ثانوية',
            'subject': 'الرياضيات',
            'rating': 5,
            'quote': 'تجربة تأسيسية ناجحة تساعدنا على التحقق من تدفق المحتوى المشترك قبل استيراد البيانات النهائية.',
            'order': 1,
            'is_active': True,
            'is_featured': True,
        },
    )


def unseed_main_foundations(apps, schema_editor):
    SiteSettings = apps.get_model('main', 'SiteSettings')
    SocialLink = apps.get_model('main', 'SocialLink')
    CTABlock = apps.get_model('main', 'CTABlock')
    FAQ = apps.get_model('main', 'FAQ')
    PageMeta = apps.get_model('main', 'PageMeta')
    RelatedLink = apps.get_model('main', 'RelatedLink')
    LegalPage = apps.get_model('main', 'LegalPage')
    Partner = apps.get_model('main', 'Partner')
    Testimonial = apps.get_model('main', 'Testimonial')

    SocialLink.objects.filter(url='https://wa.me/966500000000').delete()
    SiteSettings.objects.filter(pk=1, site_name='أكاديمية سنا').delete()
    CTABlock.objects.filter(
        slug__in=[
            'homepage-cta',
            'about-cta',
            'teachers-cta',
            'teacher-profile-cta',
            'how-it-works-cta',
            'pricing-cta',
            'blog-cta',
            'blog-post-cta',
        ]
    ).delete()
    FAQ.objects.filter(question='كيف أبدأ التسجيل في أكاديمية سنا؟').delete()
    PageMeta.objects.filter(slug__in=['home', 'faq']).delete()
    RelatedLink.objects.filter(
        title__in=['اطلع على الباقات', 'تواصل مع الفريق', 'تصفح المدونة']
    ).delete()
    LegalPage.objects.filter(slug__in=['privacy', 'terms']).delete()
    Partner.objects.filter(name='شريك تأسيسي').delete()
    Testimonial.objects.filter(student_name='طالب تجريبي', page='homepage').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_main_foundations, unseed_main_foundations),
    ]
