# Generated by Django 6.0.3 on 2026-04-02 17:40

from django.db import migrations


def seed_homepage_content(apps, schema_editor):
    AppPromoSection = apps.get_model('main', 'AppPromoSection')
    CTABlock = apps.get_model('main', 'CTABlock')
    EducationalService = apps.get_model('main', 'EducationalService')
    FAQ = apps.get_model('main', 'FAQ')
    FeatureBlock = apps.get_model('main', 'FeatureBlock')
    FeaturePoint = apps.get_model('main', 'FeaturePoint')
    FeatureTab = apps.get_model('main', 'FeatureTab')
    FeatureTabPoint = apps.get_model('main', 'FeatureTabPoint')
    HeroSection = apps.get_model('main', 'HeroSection')
    PageMeta = apps.get_model('main', 'PageMeta')
    Partner = apps.get_model('main', 'Partner')
    ProcessStep = apps.get_model('main', 'ProcessStep')
    ServiceFeature = apps.get_model('main', 'ServiceFeature')
    Testimonial = apps.get_model('main', 'Testimonial')
    TrustStat = apps.get_model('main', 'TrustStat')

    HeroSection.objects.update_or_create(
        pk=1,
        defaults={
            'headline': 'ابدأ رحلتك مع أقوى منصة تعليمية متكاملة',
            'subheading': 'الخيار الأفضل للطالب السعودي',
            'description': 'سنا هي منصة تعليمية رقمية تمنح الطالب السعودي مسارًا واضحًا مع معلمين خبراء وتقارير متابعة منظمة للأسرة.',
            'primary_cta_text': 'افتح حساب جديد',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تصفح الدورات',
            'secondary_cta_url': '/pricing/',
            'hero_image': '',
        },
    )

    stats = [
        ('+٥٠٠', 'معلمون معتمدون', 'خبرات تخصصية في المناهج الوطنية والدولية', 'users'),
        ('+١٠,٠٠٠', 'طلاب نشطون', 'من مختلف مدن المملكة وخارجها', 'students'),
        ('+٥٠,٠٠٠', 'حصص منفذة', 'متابعة دقيقة للحضور والنتائج والتوصيات', 'sessions'),
        ('٩٨٪', 'رضا الأسر', 'تقارير أسبوعية وتجربة دعم سريعة وواضحة', 'satisfaction'),
    ]
    for order, (number, label, description, icon) in enumerate(stats, start=1):
        TrustStat.objects.update_or_create(
            label=label,
            defaults={
                'number': number,
                'description': description,
                'icon': icon,
                'order': order,
                'is_active': True,
            },
        )

    services = [
        (
            'الدروس الخصوصية',
            'حصص فردية أو ثنائية مع معلمين معتمدين، مرونة في الجدولة، وتقارير مخصصة بعد كل حصة.',
            'users',
            'اعرف أكثر عن الدروس الخصوصية',
            '/teachers/',
            [
                'خطة أسبوعية واضحة',
                'معلم ثابت يتابع التقدم',
                'تقارير موجزة بعد كل حصة',
            ],
        ),
        (
            'دورات القدرات والتحصيلي',
            'تدريب منهجي على الكمي واللفظي والتحصيلي مع بنوك أسئلة واختبارات محاكية.',
            'chart-bar',
            'اكتشف دورات القدرات والتحصيلي',
            '/pricing/',
            [
                'اختبارات تشخيصية',
                'بنوك أسئلة متنوعة',
                'متابعة أسبوعية للنتائج',
            ],
        ),
        (
            'المناهج الدراسية',
            'تغطية منظمة للمناهج الوطنية والدولية، مراجعات مركزة، وواجبات موجّهة.',
            'book-open',
            'استكشف المواد الدراسية',
            '/teachers/',
            [
                'تغطية مرحلية للمحتوى',
                'مراجعات دورية للاختبارات',
                'واجبات علاجية حسب الحاجة',
            ],
        ),
    ]
    for order, (title, description, icon, cta_text, cta_url, features) in enumerate(services, start=1):
        service, _ = EducationalService.objects.update_or_create(
            title=title,
            defaults={
                'description': description,
                'icon': icon,
                'image': '',
                'cta_text': cta_text,
                'cta_url': cta_url,
                'order': order,
                'is_active': True,
            },
        )
        for feature_order, feature_text in enumerate(features, start=1):
            ServiceFeature.objects.update_or_create(
                service=service,
                text=feature_text,
                defaults={'order': feature_order},
            )

    tutoring_block, _ = FeatureBlock.objects.update_or_create(
        slug='private-tutoring',
        defaults={
            'title': 'ادرس مع معلمك الخصوصي',
            'description': 'خطة دراسية مرنة، متابعة مستمرة، وتواصل مباشر يضمن أن كل حصة تقرّب الطالب من النتيجة المطلوبة.',
            'image': '',
            'order': 1,
            'is_active': True,
        },
    )
    tutoring_points = [
        'تشخيص مستوى الطالب قبل الانطلاق ووضع هدف واضح لكل أربعة أسابيع.',
        'جدولة مرنة صباحًا ومساءً لتناسب المدرسة والأنشطة الأسرية.',
        'معلم ثابت يفهم أسلوب الطالب ويطوّر معه علاقة تعليمية مستقرة.',
        'تقارير موجزة بعد كل حصة مع توصيات منزلية قابلة للتطبيق.',
        'مراجعات قصيرة قبل الاختبارات وحلول علاجية للثغرات الحرجة.',
        'إشراك ولي الأمر في مستوى الحضور والتقدم والمهام الأسبوعية.',
    ]
    for order, point_text in enumerate(tutoring_points, start=1):
        FeaturePoint.objects.update_or_create(
            feature_block=tutoring_block,
            text=point_text,
            defaults={'order': order},
        )

    aptitude_block, _ = FeatureBlock.objects.update_or_create(
        slug='aptitude-tests',
        defaults={
            'title': 'تغلب على اختبارات القدرات والتحصيلي',
            'description': 'مسارات مركزة للكمي واللفظي والتحصيلي مع تدريب مستمر واختبارات تحاكي الواقع.',
            'image': '',
            'order': 2,
            'is_active': True,
        },
    )
    aptitude_tabs = {
        'القدرات الكمي': [
            'اختبارات تشخيصية تضع الطالب في المسار الصحيح من البداية.',
            'بنوك أسئلة ضخمة مع تصنيف حسب المهارة والزمن والصعوبة.',
            'خطة أسبوعية للمذاكرة مع متابعة مؤشرات السرعة والدقة.',
        ],
        'القدرات اللفظي': [
            'ملخصات مركزة للكلمات المفتاحية والعلاقات اللفظية.',
            'تدريبات متدرجة على استيعاب المقروء والتناظر اللفظي.',
            'تقارير تقارن الأداء الحالي بالمستوى المستهدف للاختبار.',
        ],
        'التحصيلي': [
            'مراجعات مكثفة للمقررات العلمية وفق الأوزان الفعلية للاختبار.',
            'حصص تصحيح بعد كل اختبار محاكي لاستخراج الدروس عمليًا.',
            'خطة إنقاذ سريعة للطلاب المتأخرين قبل موعد الاختبار.',
        ],
    }
    for tab_order, (tab_title, tab_points) in enumerate(aptitude_tabs.items(), start=1):
        tab, _ = FeatureTab.objects.update_or_create(
            feature_block=aptitude_block,
            title=tab_title,
            defaults={'order': tab_order},
        )
        for point_order, point_text in enumerate(tab_points, start=1):
            FeatureTabPoint.objects.update_or_create(
                tab=tab,
                text=point_text,
                defaults={'order': point_order},
            )

    partner_names = [
        'جامعة الملك سعود',
        'وزارة التعليم',
        'جامعة الملك عبدالله',
        'مؤسسة الراجحي',
        'شركة جرير',
        'المؤسسة الوطنية',
        'هيئة التعليم',
        'الصندوق التعليمي',
    ]
    foundation_partner = Partner.objects.filter(name='شريك تأسيسي').first()
    for order, name in enumerate(partner_names, start=1):
        if order == 1 and foundation_partner:
            foundation_partner.name = name
            foundation_partner.logo = ''
            foundation_partner.url = ''
            foundation_partner.order = order
            foundation_partner.is_active = True
            foundation_partner.save(update_fields=['name', 'logo', 'url', 'order', 'is_active'])
            continue
        Partner.objects.update_or_create(
            name=name,
            defaults={
                'logo': '',
                'url': '',
                'order': order,
                'is_active': True,
            },
        )

    testimonials = [
        ('طالب تجريبي', 'ط.ت', 'الرياضيات', 'الصف الثالث', 'كيف رفعت درجتي من ٦٥ إلى ٩٨'),
        ('سارة محمد', 'س.م', 'قدرات كمي', 'ثانوي', 'تأسيس ممتاز وطريقة شرح واضحة'),
        ('عبدالله ناصر', 'ع.ن', 'الفيزياء', 'متقدم', 'المعلم مهتم جداً والمراجعة دقيقة'),
        ('ولية أمر', 'و.أ', 'متابعة أسرية', 'أولياء الأمور', 'التقارير اليومية سهّلت علينا المتابعة'),
    ]
    for order, (student_name, initials, subject, level, quote) in enumerate(testimonials, start=1):
        Testimonial.objects.update_or_create(
            student_name=student_name,
            page='homepage',
            defaults={
                'student_initials': initials,
                'level': level,
                'subject': subject,
                'rating': 5,
                'quote': quote,
                'order': order,
                'is_active': True,
                'is_featured': order == 1,
            },
        )

    steps = [
        ('اختر المادة', 'حدد المادة أو الاختبار والمرحلة الحالية لنقترح لك المسار الأنسب.'),
        ('اختر المعلم', 'راجع الملفات والخبرات والتقييمات ثم اختر المعلم الذي يناسب هدفك.'),
        ('احجز الحصة', 'اختر الموعد المناسب واستلم خطة الحصة الأولى قبل بدايتها بوقت كافٍ.'),
        ('ابدأ التعلم', 'تابع تقدمك واستلم التقارير وكرّر ما يلزم حتى تثبت النتيجة المطلوبة.'),
    ]
    for order, (title, description) in enumerate(steps, start=1):
        ProcessStep.objects.update_or_create(
            title=title,
            defaults={
                'step_number': order,
                'description': description,
                'icon': '',
                'order': order,
                'is_active': True,
            },
        )

    homepage_faqs = [
        ('كيف أبدأ التسجيل في أكاديمية سنا؟', 'ابدأ باختيار المسار المناسب من الصفحة الرئيسية أو تواصل معنا مباشرة عبر واتساب ثم نرشح لك المعلم الأنسب.'),
        ('هل يمكن للطالب تغيير المعلم إذا لم يشعر بالانسجام؟', 'نعم، نراجع التجربة مع الطالب وولي الأمر ونرتب انتقالًا سلسًا عند الحاجة.'),
        ('ما الفرق بين الدروس الخصوصية وباقات القدرات؟', 'الدروس الخصوصية تركز على المنهج الدراسي، بينما باقات القدرات والتحصيلي مبنية على مهارات الاختبار والتحليل.'),
        ('كيف تتم متابعة مستوى الطالب بعد كل حصة؟', 'نرسل تقريرًا موجزًا يتضمن ما تم إنجازه ونقاط القوة والتوصيات العملية للأسرة.'),
        ('هل توجد باقات شهرية أم الدفع لكل حصة؟', 'نوفر الطريقتين بحسب المسار، مع مرونة أعلى في المواسم الدراسية وفترات الاختبارات.'),
        ('هل تقدمون خططًا خاصة للقدرات اللفظي والكمي؟', 'نعم، يمكن بناء خطة متوازنة أو التركيز على المحور الأضعف حسب حاجة الطالب.'),
        ('ما أوقات الحصص المتاحة؟', 'نعمل على مدى اليوم مع مرونة أعلى في الفترات المسائية ومسارات مكثفة عند الحاجة.'),
        ('هل المنصة مناسبة للطالب الذي يحتاج متابعة لصيقة؟', 'لدينا إشعارات واضحة وتقارير دورية وتوصيات عملية تجعل المتابعة اليومية أسهل للأسرة.'),
        ('هل يمكن الجمع بين الدروس الخصوصية والقدرات في نفس الحساب؟', 'نعم، ويمكن تنسيق الجدول بحيث لا يتعارض المساران مع التزامات الطالب.'),
        ('كيف يمكنني التواصل السريع مع فريق الدعم؟', 'أسرع قناة هي واتساب، كما يمكنك استخدام نموذج التواصل أو البريد الإلكتروني.'),
    ]
    for order, (question, answer) in enumerate(homepage_faqs, start=1):
        FAQ.objects.update_or_create(
            question=question,
            defaults={
                'answer': answer,
                'category': 'general' if order in (1, 2, 4, 7, 8, 10) else 'platform',
                'order': order,
                'is_active': True,
                'show_on_homepage': True,
            },
        )

    AppPromoSection.objects.update_or_create(
        pk=1,
        defaults={
            'title': 'معك في كل مكان',
            'subtitle': 'منصتك في كل وقت',
            'description': 'افتح الخطة الدراسية، راجع تقرير الحصة، وتابع المهام القادمة من الجوال أو الجهاز اللوحي.',
            'preview_image': '',
            'google_play_url': 'https://play.google.com/store/apps/details?id=sanaacademy',
            'app_store_url': 'https://apps.apple.com/app/sana-academy/id000000000',
            'is_active': True,
        },
    )

    CTABlock.objects.update_or_create(
        slug='homepage-cta',
        defaults={
            'heading': 'لا تفوّت فرصة التفوق الدراسي',
            'subheading': 'الخطوة التالية',
            'body_text': 'ابدأ اليوم بخطة واضحة، ومعلم مناسب، وتجربة تزيل الحيرة من قرار الأسرة.',
            'primary_cta_text': 'سجّل الآن',
            'primary_cta_url': '/pricing/',
            'secondary_cta_text': 'تواصل عبر الواتساب',
            'secondary_cta_url': 'https://wa.me/966500000000',
            'social_proof_text': 'انضم إلى أكثر من ١٠,٠٠٠ طالب اختاروا تجربة تعليمية أكثر وضوحًا وثقة.',
            'is_active': True,
        },
    )

    PageMeta.objects.update_or_create(
        slug='home',
        defaults={
            'meta_title': 'أكاديمية سنا | منصة تعليمية سعودية متكاملة',
            'meta_description': 'منصة تعليمية عربية تقدم دروسًا خصوصية ومسارات قدرات وتحصيلي ومعلمين معتمدين.',
            'is_active': True,
        },
    )


def unseed_homepage_content(apps, schema_editor):
    AppPromoSection = apps.get_model('main', 'AppPromoSection')
    EducationalService = apps.get_model('main', 'EducationalService')
    FeatureBlock = apps.get_model('main', 'FeatureBlock')
    HeroSection = apps.get_model('main', 'HeroSection')
    ProcessStep = apps.get_model('main', 'ProcessStep')
    Testimonial = apps.get_model('main', 'Testimonial')
    TrustStat = apps.get_model('main', 'TrustStat')

    HeroSection.objects.filter(pk=1).delete()
    TrustStat.objects.filter(
        label__in=['معلمون معتمدون', 'طلاب نشطون', 'حصص منفذة', 'رضا الأسر']
    ).delete()
    EducationalService.objects.filter(
        title__in=['الدروس الخصوصية', 'دورات القدرات والتحصيلي', 'المناهج الدراسية']
    ).delete()
    FeatureBlock.objects.filter(slug__in=['private-tutoring', 'aptitude-tests']).delete()
    ProcessStep.objects.filter(
        title__in=['اختر المادة', 'اختر المعلم', 'احجز الحصة', 'ابدأ التعلم']
    ).delete()
    Testimonial.objects.filter(
        student_name__in=['طالب تجريبي', 'سارة محمد', 'عبدالله ناصر', 'ولية أمر'],
        page='homepage',
    ).delete()
    AppPromoSection.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apppromosection_educationalservice_featureblock_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_homepage_content, unseed_homepage_content),
    ]
