# Generated by Django 6.0.3 on 2026-04-02 19:29

from django.db import migrations


CURATED_FAQ_QUESTIONS = [
    'كيف أبدأ التسجيل في أكاديمية سنا؟',
    'هل يمكن للطالب تغيير المعلم إذا لم يشعر بالانسجام؟',
    'ما هي المواد والمراحل الدراسية التي تغطونها؟',
    'ما هي أسعار الحصص الخصوصية؟',
    'هل توجد خصومات للباقات المكثفة؟',
    'هل يمكنني استرداد المبلغ إذا لم أكن راضيًا؟',
    'كيف تختارون المعلمين في المنصة؟',
    'هل يمكنني اختيار معلم معين بنفسي؟',
    'هل جميع المعلمين معتمدون؟',
    'ما هي أوقات الحصص المتاحة؟',
    'هل يمكنني إعادة جدولة حصة؟',
    'كم مدة الحصة الواحدة؟',
    'كيف تتم الحصص أونلاين؟',
    'هل تسجلون الحصص للمراجعة؟',
    'كيف يمكنني متابعة تقدم ابني؟',
    'هل أحتاج إلى تثبيت برامج خاصة؟',
]

STALE_FAQ_QUESTIONS = [
    'ما الفرق بين الدروس الخصوصية وباقات القدرات؟',
    'كيف تتم متابعة مستوى الطالب بعد كل حصة؟',
    'هل توجد باقات شهرية أم الدفع لكل حصة؟',
    'هل تقدمون خططًا خاصة للقدرات اللفظي والكمي؟',
    'ما أوقات الحصص المتاحة؟',
    'هل المنصة مناسبة للطالب الذي يحتاج متابعة لصيقة؟',
    'هل يمكن الجمع بين الدروس الخصوصية والقدرات في نفس الحساب؟',
    'كيف يمكنني التواصل السريع مع فريق الدعم؟',
]

CURATED_RELATED_LINK_TITLES = [
    'كيف نعمل',
    'الأسعار والباقات',
    'تواصل معنا',
]

STALE_RELATED_LINK_TITLES = [
    'اطلع على الباقات',
    'تواصل مع الفريق',
    'تصفح المدونة',
]


def cleanup_faq_catalog(apps, schema_editor):
    FAQ = apps.get_model('main', 'FAQ')
    RelatedLink = apps.get_model('main', 'RelatedLink')

    FAQ.objects.filter(question__in=STALE_FAQ_QUESTIONS).update(
        is_active=False,
        show_on_homepage=False,
    )
    FAQ.objects.filter(question__in=CURATED_FAQ_QUESTIONS).update(is_active=True)

    RelatedLink.objects.filter(title__in=STALE_RELATED_LINK_TITLES).update(is_active=False)
    RelatedLink.objects.filter(title__in=CURATED_RELATED_LINK_TITLES).update(is_active=True)


def uncleanup_faq_catalog(apps, schema_editor):
    FAQ = apps.get_model('main', 'FAQ')
    RelatedLink = apps.get_model('main', 'RelatedLink')

    FAQ.objects.filter(question__in=STALE_FAQ_QUESTIONS).update(is_active=True)
    RelatedLink.objects.filter(title__in=STALE_RELATED_LINK_TITLES).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seed_faq_page_content'),
    ]

    operations = [
        migrations.RunPython(cleanup_faq_catalog, uncleanup_faq_catalog),
    ]
