# Generated by Django 6.0.3 on 2026-04-02 19:58

from django.db import migrations


PRIVACY_CONTENT = """
<p class="text-lg leading-relaxed text-slate-700">في أكاديمية سنا، نلتزم بحماية خصوصيتك وبياناتك الشخصية. توضح سياسة الخصوصية هذه كيفية جمع بياناتك واستخدامها وحمايتها عند استخدام منصتنا التعليمية.</p>
<h2>١. البيانات التي نجمعها</h2>
<p>نجمع أنواعًا مختلفة من البيانات لتقديم خدماتنا وتحسين تجربتك:</p>
<ul class="mr-6 space-y-2">
  <li><strong>البيانات الشخصية:</strong> الاسم الكامل، البريد الإلكتروني، رقم الجوال، تاريخ الميلاد، المدينة.</li>
  <li><strong>بيانات الحساب:</strong> اسم المستخدم، كلمة المرور المشفرة، وإعدادات الحساب.</li>
  <li><strong>بيانات الاستخدام:</strong> سجل الحصص، الدورات المسجلة، التقدم الدراسي، ونتائج الاختبارات.</li>
  <li><strong>بيانات الدفع:</strong> معلومات الفوترة ولا نخزن بيانات البطاقة كاملة.</li>
  <li><strong>بيانات الجهاز:</strong> عنوان IP، نوع المتصفح، نوع الجهاز، ونظام التشغيل.</li>
</ul>
<h2>٢. كيف نستخدم بياناتك</h2>
<p>نستخدم البيانات التي نجمعها لتقديم الخدمات التعليمية، وإدارة الحساب، وحجز الحصص، وتتبع التقدم الدراسي، وإرسال الإشعارات، وتحسين المنصة، وتقديم دعم العملاء، ومعالجة المدفوعات، والامتثال للمتطلبات القانونية.</p>
<h2>٣. مشاركة البيانات</h2>
<p>نحترم خصوصيتك ولا نبيع بياناتك الشخصية. قد نشارك بياناتك مع المعلمين، ومزودي الخدمة، وعند وجود متطلبات قانونية، أو لحماية حقوق المنصة وسلامة المستخدمين.</p>
<h2>٤. ملفات تعريف الارتباط</h2>
<p>نستخدم ملفات تعريف الارتباط الضرورية والتحليلية وملفات التفضيلات لتحسين تجربتك، ويمكنك التحكم فيها من إعدادات المتصفح.</p>
<h2>٥. أمان البيانات</h2>
<ul class="mr-6 space-y-2">
  <li>تشفير البيانات أثناء النقل باستخدام SSL/TLS.</li>
  <li>تشفير كلمات المرور بخوارزميات قوية.</li>
  <li>تخزين البيانات في خوادم آمنة ومراقبة مستمرة للتهديدات.</li>
  <li>التحقق من الهوية للوصول إلى البيانات الحساسة.</li>
</ul>
<h2>٦. حقوقك</h2>
<p>لديك حق الوصول إلى بياناتك وتصحيحها وحذفها في الحالات المناسبة والاعتراض على بعض المعالجات وطلب نقل البيانات. للتواصل بشأن ذلك استخدم البريد <a href="mailto:privacy@premiumacademy.sa">privacy@premiumacademy.sa</a>.</p>
<h2>٧. خصوصية الأطفال</h2>
<p>خدماتنا موجهة للطلاب من جميع الأعمار، ويستلزم التسجيل للطلاب دون ١٨ عامًا موافقة ولي الأمر، مع جمع الحد الأدنى من البيانات اللازمة لتقديم الخدمة.</p>
<h2>٨. التعديلات على السياسة</h2>
<p>قد نقوم بتحديث هذه السياسة من وقت لآخر وسنخطرك بأي تغييرات جوهرية عبر المنصة أو البريد الإلكتروني مع تحديث تاريخ آخر مراجعة.</p>
<h2>٩. التواصل</h2>
<ul class="mr-6 space-y-2">
  <li>البريد الإلكتروني: <a href="mailto:privacy@premiumacademy.sa">privacy@premiumacademy.sa</a></li>
  <li>الهاتف: <a href="tel:+966114000000">+966 11 400 0000</a></li>
  <li>العنوان: الرياض، المملكة العربية السعودية</li>
</ul>
"""

TERMS_CONTENT = """
<p class="text-lg leading-relaxed text-slate-700">مرحبًا بك في أكاديمية سنا. باستخدامك لمنصتنا وخدماتنا فإنك توافق على الالتزام بالشروط والأحكام الموضحة أدناه. يرجى قراءة هذه الشروط بعناية قبل استخدام المنصة.</p>
<h2>١. نطاق الاستخدام</h2>
<p>توفر أكاديمية سنا منصة تعليمية إلكترونية تقدم دروسًا خصوصية عبر الإنترنت للطلاب في المملكة العربية السعودية. يشمل استخدام المنصة الوصول إلى المحتوى التعليمي وحجز الحصص والمشاركة في الدورات التدريبية.</p>
<h2>٢. إنشاء الحسابات</h2>
<p>لاستخدام خدماتنا يجب إنشاء حساب مستخدم بمعلومات صحيحة ومحدثة. أنت مسؤول عن سرية بيانات الدخول وعن جميع الأنشطة التي تتم تحت حسابك.</p>
<h2>٣. الرسوم والمدفوعات</h2>
<p>تقدم المنصة باقات اشتراك متنوعة بأسعار مختلفة تُعرض بوضوح على صفحة الأسعار. قد تتغير الأسعار مع إشعار مسبق، وتتم المدفوعات بوسائل آمنة ومشفرة.</p>
<h2>٤. سياسة الاسترداد</h2>
<p>يمكن طلب الاسترداد خلال ٧ أيام من تاريخ الشراء إذا لم تُستهلك أكثر من حصتين دراسيتين. تعالج الطلبات خلال ١٤ يوم عمل وفق شروط الباقة.</p>
<h2>٥. حقوق الملكية الفكرية</h2>
<p>جميع المحتويات الموجودة على المنصة بما في ذلك النصوص والصور والمواد التعليمية محمية بموجب قوانين الملكية الفكرية، ويُحظر نسخها أو توزيعها دون إذن مسبق.</p>
<h2>٦. الخصوصية والبيانات</h2>
<p>نلتزم بحماية خصوصيتك ويتم جمع واستخدام بياناتك وفقًا لسياسة الخصوصية الخاصة بنا. لمزيد من التفاصيل يرجى مراجعة <a href="/privacy/">سياسة الخصوصية</a>.</p>
<h2>٧. إنهاء الخدمة</h2>
<p>نحتفظ بالحق في تعليق أو إنهاء حسابك عند انتهاك هذه الشروط، ويمكنك إنهاء اشتراكك في أي وقت من خلال إعدادات الحساب أو التواصل مع خدمة العملاء.</p>
<h2>٨. التعديلات على الشروط</h2>
<p>نحتفظ بالحق في تعديل هذه الشروط في أي وقت، وسيتم إشعارك بأي تغييرات جوهرية عبر البريد الإلكتروني أو من خلال المنصة.</p>
<h2>٩. القانون المطبق</h2>
<p>تخضع هذه الشروط والأحكام وتُفسر وفقًا لقوانين المملكة العربية السعودية، وأي نزاعات تنشأ عن استخدام المنصة تُحال إلى المحاكم المختصة في الرياض.</p>
<h2>١٠. التواصل</h2>
<ul class="mr-6 space-y-2">
  <li>البريد الإلكتروني: <a href="mailto:legal@premiumacademy.sa">legal@premiumacademy.sa</a></li>
  <li>الهاتف: <a href="tel:+966114000000">+966 11 400 0000</a></li>
  <li>العنوان: الرياض، المملكة العربية السعودية</li>
</ul>
"""


def finalize_sitewide_content(apps, schema_editor):
    LegalPage = apps.get_model('main', 'LegalPage')
    PageMeta = apps.get_model('main', 'PageMeta')
    SiteSettings = apps.get_model('main', 'SiteSettings')
    SocialLink = apps.get_model('main', 'SocialLink')

    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            'site_name': 'أكاديمية سنا',
            'site_description': 'منصة تعليمية عربية متكاملة للدروس الخصوصية والقدرات والتحصيلي مع تجربة رقمية واضحة وموثوقة للطلاب والأسر.',
            'phone': '+966 11 400 0000',
            'email': 'hello@premiumacademy.sa',
            'whatsapp': '966500000000',
            'address': 'الرياض، المملكة العربية السعودية',
            'google_maps_url': 'https://maps.google.com/?q=Riyadh',
            'copyright_text': '© 2026 أكاديمية سنا. جميع الحقوق محفوظة.',
            'accreditation_text': 'أكاديمية سنا معتمدة من الجهات التعليمية المختصة وتلتزم بأعلى معايير الجودة في تقديم الخدمات التعليمية.',
        },
    )

    social_links = [
        ('whatsapp', 'https://wa.me/966500000000'),
        ('instagram', 'https://instagram.com/premiumacademy.sa'),
        ('x', 'https://x.com/premiumacademy_sa'),
        ('tiktok', 'https://tiktok.com/@premiumacademy.sa'),
        ('linkedin', 'https://linkedin.com/company/premiumacademy-sa'),
        ('youtube', 'https://youtube.com/@premiumacademy-sa'),
        ('facebook', 'https://facebook.com/premiumacademy.sa'),
    ]
    site_settings = SiteSettings.objects.get(pk=1)
    for order, (platform, url) in enumerate(social_links, start=1):
        SocialLink.objects.update_or_create(
            site_settings=site_settings,
            platform=platform,
            defaults={
                'url': url,
                'order': order,
                'is_active': True,
            },
        )

    PageMeta.objects.update_or_create(
        slug='home',
        defaults={
            'meta_title': 'أكاديمية سنا | منصة تعليمية سعودية متكاملة',
            'meta_description': 'منصة تعليمية عربية تقدم دروسًا خصوصية ومسارات قدرات وتحصيلي ومعلمين معتمدين بتجربة رقمية واضحة وعالية الثقة.',
            'is_active': True,
        },
    )
    PageMeta.objects.update_or_create(
        slug='faq',
        defaults={
            'meta_title': 'الأسئلة الشائعة | أكاديمية سنا',
            'meta_description': 'إجابات شاملة على الأسئلة الشائعة حول خدمات أكاديمية سنا وطريقة الحجز والمتابعة.',
            'is_active': True,
        },
    )

    LegalPage.objects.update_or_create(
        slug='privacy',
        defaults={
            'title': 'سياسة الخصوصية',
            'content': PRIVACY_CONTENT,
            'meta_title': 'سياسة الخصوصية | أكاديمية سنا',
            'meta_description': 'سياسة الخصوصية الخاصة بمنصة أكاديمية سنا والتزامات حماية البيانات والخصوصية.',
        },
    )
    LegalPage.objects.update_or_create(
        slug='terms',
        defaults={
            'title': 'الشروط والأحكام',
            'content': TERMS_CONTENT,
            'meta_title': 'الشروط والأحكام | أكاديمية سنا',
            'meta_description': 'الشروط والأحكام الخاصة باستخدام منصة أكاديمية سنا للتعليم الإلكتروني.',
        },
    )


def unfinalize_sitewide_content(apps, schema_editor):
    LegalPage = apps.get_model('main', 'LegalPage')
    SiteSettings = apps.get_model('main', 'SiteSettings')
    SocialLink = apps.get_model('main', 'SocialLink')

    SocialLink.objects.filter(
        url__in=[
            'https://instagram.com/premiumacademy.sa',
            'https://x.com/premiumacademy_sa',
            'https://tiktok.com/@premiumacademy.sa',
            'https://linkedin.com/company/premiumacademy-sa',
            'https://youtube.com/@premiumacademy-sa',
            'https://facebook.com/premiumacademy.sa',
        ]
    ).delete()
    SiteSettings.objects.filter(pk=1).update(
        email='info@premiumacademy.sa',
    )
    LegalPage.objects.filter(slug='privacy').update(
        content='محتوى تأسيسي لصفحة سياسة الخصوصية سيتم استبداله بالنص النهائي أثناء مرحلة الصفحات القانونية.',
    )
    LegalPage.objects.filter(slug='terms').update(
        content='محتوى تأسيسي لصفحة الشروط والأحكام سيتم استبداله بالنص النهائي أثناء مرحلة الصفحات القانونية.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cleanup_faq_catalog'),
    ]

    operations = [
        migrations.RunPython(finalize_sitewide_content, unfinalize_sitewide_content),
    ]
